### ISSUE TITLE
MFXTextField weird behaivor inside GridPane

### ISSUE THREAD

**Issue by Luposz** [palexdev/MaterialFX#100]
I don't know if this is intended
Inside a GridPane MFXTextField doesn't adapt to the column width size. It's needed to change Max Width value to MAX_VALUE to grow with the GridPane.
Before Max Width change
![MFXTextField](https://user-images.githubusercontent.com/89623719/131427870-9296c432-d94b-4804-9932-7dad972b5142.PNG)

After Max Width change
![MFXTextField2](https://user-images.githubusercontent.com/89623719/131427941-08d72eaa-8ba5-42ea-a459-8d8abd482f32.PNG)

Also, sometimes overlap when column size it's "small" for the MFXTextField.
For this problem, it's needed to change the Min Width property of the MFXTextField to the same value that the Column Min Widht Value.
![MFXTextField Grid](https://user-images.githubusercontent.com/89623719/131428479-6e5bc28b-1a6b-44f4-b9d6-8c13d2f1dda7.PNG)

After the change.
![MFXTextField Grid2](https://user-images.githubusercontent.com/89623719/131428642-aa53e35c-8273-4ad2-a2ca-c3169be1d4ca.PNG)

**Comment by Kilobyte1000** [comment]
This is the intended behaviour of all javafx controls. They are not resized beyond their min and Max dimensions by layout managers. If you want the MFXTextField to adapt to GridPane set Min and Max dimensions to MIN_VALUE and MAX_VALUE

**Comment by palexdev** [comment]
@Luposz can you please share a reproducible example? Even a FXML is fine, make sure to include both examples in the FXML though

@Kilobyte1000 not exactly, I think MFXTextFieldSkin overrides the behavior of the original skin, TextFieldSkin
I want to check it and eventually improve it

**Comment by Kilobyte1000** [comment]
[An FXML demonstrating the issue](https://github.com/palexdev/MaterialFX/files/7268618/fxml.zip), the same problem also affects MFXTextField in a VBox.

**Comment by palexdev** [comment]
I can confirm this is the intended behavior for MFXTextFields
In latest version they behave the same
They tend to always use the preferred width unless you set them to take all the space available
As for the height, you should not force the height to be lesser than the recommended minimum, especially with new fields
