### ISSUE TITLE
MFXToggleButton ignores text color 

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#105]
MFXToggleButton ignores the -fx-text-fill its always black without option to change it

**Comment by palexdev** [comment]
Are you using your own stylesheet to customize the text?

**Comment by brandonrock919** [comment]
yes I also tried through scene builder on scene builder it shows the customized color but when I launch the app its shows black again

**Comment by palexdev** [comment]
I think this is due to a JavaFX's bug related to the userAgentStylesheet, currently under review [Mailing List](https://mail.openjdk.java.net/pipermail/openjfx-dev/2021-September/032185.html)
Can you share the CSS here please?

**Comment by brandonrock919** [comment]
I don't think there is a issue with JavaFX because all other styles applied besides of text-fill

for example 
#toggle {
    -fx-text-fill: #fafafa;
    -mfx-toggle-color: #fafafa;
    -mfx-toggle-line-color: rgb(34, 139, 73);
    -mfx-untoggle-color: #fafafa;
    -mfx-untoggle-line-color: rgb(61, 61, 61);
    -mfx-size: 10;
}

**Comment by palexdev** [comment]
I'm not able to reproduce the issue though

This is for a running application:
![image](https://user-images.githubusercontent.com/16880178/135314960-37ebbfec-541d-4544-be44-5388d4eb6dff.png)

And this is from SceneBuilder:
![image](https://user-images.githubusercontent.com/16880178/135315032-4e94279c-0a64-4525-bfb4-9463046856f6.png)

Both are correctly styled

**Comment by brandonrock919** [comment]
There is a text ?
I see in your example the style are correct but where is the text try to put for example blue background ? you will be able to see the toggle text in white color ?

**Comment by palexdev** [comment]
Latest version improved CSS support for MaterialFX, issue should be resolved
