### ISSUE TITLE
MFXRectangleToggleNode ignores color options

### ISSUE THREAD

**Issue by mat1911** [palexdev/MaterialFX#106]
When I try to change "selected color" or "unselected color" for MFXRectangleToggleNode all my choices are ignored (no matter if I use scene builder or do it in code).

**Comment by palexdev** [comment]
Can you share a minimal reproducible example please?

**Comment by mat1911** [comment]
The example is given below:

![image](https://user-images.githubusercontent.com/46813657/135746949-4cd0920b-3ace-4763-8639-7df4345d5045.png)

I am using Scene Builder 17.0.0. As you can see I have changed the "Selected Color" and "Unselected Color" properties but the toggle is still white/gray. I also tried to inject it into the controller by using @FXML annotation and then set its color with method setSelectedColor() but the result is always the same.

**Comment by mat1911** [comment]
I would like to add that color change works in scene builder if I use styles like: -mfx-selected-color: #000000.

**Comment by palexdev** [comment]
Latest released version improved CSS support for MaterialFX, as a consequence many stylesheets have been reviewed too
Issue should be resolved
