### ISSUE TITLE
Creating custom Modals?

### ISSUE THREAD

**Issue by wooneusean** [palexdev/MaterialFX#108]
Hello, I'm trying to create custom modals. I want to load them from FXML with their controllers attached.

I have achieved somewhat of a success by creating an empty subclass of `AbstractMFXDialog` and setting the content of it to FXML loaded beforehand. My code below shows what I mean:

```java
MFXStageDialog dialog = new MFXStageDialog();
CustomMFXDialog content = new CustomMFXDialog();

Parent root = null;
try {
    FXMLLoader loader = new FXMLLoader(MainApplication.class.getResource("path/to/view.fxml"));
    root = loader.load();
} catch (IOException e) {
    e.printStackTrace();
}

content.setCenter(root);

dialog.setOwner(owner);

dialog.setDialog(content);
dialog.setModality(Modality.APPLICATION_MODAL);

dialog.setScrimOpacity(0.75);
dialog.setScrimBackground(true);

dialog.show();
```

However, this makes it hard to get a handle on the `MFXStageDialog` in my controller.

This makes it so I can't properly close the stage dialog, for example, I tried closing the modal by getting the `Window` object, casting it to a `Stage` object and calling `stage.close()`. However, that doesn't remove the scrim and probably is a bad way to do it.

Unless I get the controller when loading the FXML and set it there, there is no elegant way of doing this.

Is there a way you could recommend to overcome this problem?

**Comment by palexdev** [comment]
Dialogs have been reworked in latest version
Now MFXStageDialog also offers some static methods to load the dialog's content from a FXML file
