### ISSUE TITLE
Feature Request - Dialog using Node for content instead of String

### ISSUE THREAD

**Issue by DaRealTurtyWurty** [palexdev/MaterialFX#109]
I have just started looking into using `AbstractMFXDialog`s for my project, and it seems fantastic, but there seem to be quite a few limitations. One of these is not being able to have hyperlinks inside of the text, since it only allows a `String` for the content and not, say a `Node` or at least a `TextFlow`.

If there is a way to do this already, I can't find any documentation or easy way to do it. So if this could be added that'd be super helpful.

**Comment by palexdev** [comment]
Latest version changed the dialogs, it should be easier now
