### ISSUE TITLE
How to Styling MFXComboBox button's label

### ISSUE THREAD

**Issue by n7484443** [palexdev/MaterialFX#111]
I tried changing MFXComboBox selection style.
![image](https://user-images.githubusercontent.com/7384324/138437498-5c10c3a0-54c7-44e4-a6fd-995e7dad45f8.png)
It doesn't work only on the select button's label. It works good on other labels in combo box.
```
combo_text_font.selectedValueProperty().getValue().setStyle("-fx-font-family: " + newVal.getText() + ";");
combo_text_font.getSelectedValue().setStyle("-fx-font-family: " + newVal.getText() + ";");
combo_text_font.setStyle("-fx-font-family: " + newVal.getText() + ";");
combo_text_font.getStyleClass().add("-fx-font-family: " + newVal.getText() + ";");
```
everything didn't work...

```
public MFXComboBox<Label> combo_text_font;
```
Is there a way to solve this problem? It's just bug or unsupported function?

**Comment by palexdev** [comment]
Latest version has improved CSS support for MaterialFX, issue should be fixes
