### ISSUE TITLE
Translation of English text to to other languages

### ISSUE THREAD

**Issue by Fruit-Punch-Samurai** [palexdev/MaterialFX#112]
Hi, I was wondering if there was a way to manually change/translate the current text used in components like "MFXTableView" to other languages?
If not, I would be interested in translating it myself (French and Arabic).

**Comment by palexdev** [comment]
@Fruit-Punch-Samurai internationalization API is now available on the staging branch
If you want you can provide the resource bundles you need with a PR

**Comment by Fruit-Punch-Samurai** [comment]
@palexdev Great, I will be sending a PR in a couple of days with the french translation.

**Comment by palexdev** [comment]
> @palexdev Great, I will be sending a PR in a couple of days with the french translation.

Thank you very much 👍🏻

**Comment by Fruit-Punch-Samurai** [comment]
Pull request added #132

**Comment by Laritello** [comment]
Added a pull request for the Russian language #134

**Comment by palexdev** [comment]
> Added a pull request for the Russian language #134

Good, thanks!  👍🏻
I'll merge as soon as possible, I'm currently making some changes on the staging branch

**Comment by palexdev** [comment]
Internationalization now available in the latest release

**Comment by Fruit-Punch-Samurai** [comment]
Pull request for the Arabic language added #137
