### ISSUE TITLE
Can't import materialfx in my Controller.

### ISSUE THREAD

**Issue by Nico-Src** [palexdev/MaterialFX#113]
In my FXML File i imported materialfx and everything is working fine. In my Controller and all other classes i cannot import materialfx. Module not found is the error i get but i added it with the jar file. I tried installing the depency still no success. I am using Java JDK 16 btw.

![image](https://user-images.githubusercontent.com/68270525/138595252-59b8cbcd-4dfe-41fd-ab8f-e2cca2e4c695.png)
![image](https://user-images.githubusercontent.com/68270525/138595262-557e539f-726b-4f70-8f80-60bff748ff3e.png)
![image](https://user-images.githubusercontent.com/68270525/138595271-177e7047-f9a8-4894-a592-9b3bf49fbf80.png)

**Comment by cachandlerdev** [comment]
To add clarification for anyone else who finds this and didn't understand how the previous poster fixed the issue (like myself), you need to add `requires MaterialFX;` to your `module-info.java` file.
