### ISSUE TITLE
Issues with jlink and reactfx automatic module

### ISSUE THREAD

**Issue by Fiskeboat** [palexdev/MaterialFX#118]
Hey :)
I have a modular project built with maven, and when running mvn javafx:jlink
I am met with this error;

> Error: automatic module cannot be used with jlink: reactfx from file:///C:/Users/tiger/.m2/repository/org/reactfx/reactfx/2.0-M5/reactfx-2.0-M5.jar

My pom has the following dependencies

> <dependency>

>         <dependency>
>             <groupId>org.reactfx</groupId>
>             <artifactId>reactfx</artifactId>
>             <version>2.0-M5</version>
>         </dependency> 

and

>         <dependency>
>             <groupId>io.github.palexdev</groupId>
>             <artifactId>materialfx</artifactId>
>             <version>11.12.0</version>
>         </dependency>

My module-info looks like this

> module casino.ui {
>     requires casino.core;
>     requires javafx.controls;
>     requires javafx.media;
>     requires javafx.fxml;
>     requires MaterialFX;
>     requires reactfx;
>     opens casino.ui to javafx.graphics, javafx.fxml;
> }
> 

But the requires reactfx is flagged as unstable, with the following error;

> Name of automatic module 'reactfx' is unstable, it is derived from the module's file name.Java(8390069)

Any help would be appreciated
(ps, not an actual casino, just a school project :p)

**Comment by palexdev** [comment]
Latest version doesn't use ReactFX and Flowless anymore, can't fix
