### ISSUE TITLE
Request for MFXSearchableComboBox

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#12]
Reference : https://github.com/controlsfx/controlsfx/blob/jfx-13/controlsfx-samples/src/main/java/org/controlsfx/samples/HelloSearchableComboBox.java

**Comment by palexdev** [comment]
Hey @brandonrock919 I have pushed a new commit on the staging branch that adds the requested control. It is not finished yet, but it should be usable, if you want you can try it before I complete it and push on the main branch

**Comment by palexdev** [comment]
Control added in the latest version.
