### ISSUE TITLE
MFXDatePicker / MFXComboBox not exists on scene builder

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#129]
First of all most to say the new version is outstanding cool features i like it !
The issue is that i reimport the library with the new version to scene builder but i not able to see the MFXDatePicker and MFXComboBox not exists
Thanks :)

**Comment by palexdev** [comment]
Ah I see you changed the title
I was about to say, "I bet you can't even see combo boxes and lists"
That's because some MaterialFX controls (the ones with lists  mainly) depend on [VirtualizedFX](https://github.com/palexdev/virtualizedfx), so it must be on the classpath
On SceneBuilder simply add this library too

I'm closing the issue as I'm pretty sure this is the solution, if not feel free to re-open it, and of course feel free to comment
Also, I think I'm gonna change the title and pin the issue as it may be useful for others

**Comment by javasuns** [comment]
I have VirtualizedFX as well on SceneBuilder, but I cannot see the MFXStepper control.
Am I missing something?
![image](https://github.com/palexdev/MaterialFX/assets/13131668/99e5ecf1-086f-4966-9bcd-b5deaabf53ca)

**Comment by palexdev** [comment]
> I have VirtualizedFX as well on SceneBuilder, but I cannot see the MFXStepper control. Am I missing something? ![image](https://user-images.githubusercontent.com/13131668/262923023-99e5ecf1-086f-4966-9bcd-b5deaabf53ca.png)

Import all the components, then check the SceneBuilder logs. Some exception may have occurred that is preventing the stepper to show up

**Comment by javasuns** [comment]
Well no logs are written. I am using SceneBuilder 20. I tried to run it through command line to capture the console output, but still nothing.

![image](https://github.com/palexdev/MaterialFX/assets/13131668/7df879a7-b12f-425f-b67f-427159caf7ff)

**Comment by javasuns** [comment]
![image](https://github.com/palexdev/MaterialFX/assets/13131668/8a657865-1cdc-4941-b129-902f5ccfed91)
Well now, it appeared. (I installed SceneViewer again) 
However, as you may see, I have not added VirtualizedFX and ComboBox component is already there (in the original post, it says that I needed to add VirtualizedFX for it to work)

**Comment by palexdev** [comment]
> Well now, it appeared. (I installed SceneViewer again) However, as you may see, I have not added VirtualizedFX and ComboBox component is already there (in the original post, it says that I needed to add VirtualizedFX for it to work)
Great!
Strange they are showing up, can you also use them in a Scene?

**Comment by javasuns** [comment]
You are right. It does not work without VirtualizedFX :)

In order to make MFXStepper to appear, I needed to restart SceneBuilder after adding both VirtualizedFx and MaterialFX.
