### ISSUE TITLE
MFXDatePicker styling isn't working

### ISSUE THREAD

**Issue by Laritello** [palexdev/MaterialFX#131]
Hi! I'm trying to change default colors of controls to suit my app's color scheme.  But when I tried to do the same for DatePicker I've found out that some colors aren't changing. Specifically the name of the month and year when focused.
![image](https://user-images.githubusercontent.com/29901577/152429509-124b5fde-34c1-4284-ba11-0092fc19e623.png)

Here's my CSS:
```
.mfx-date-picker .date-picker-popup .years-combo:focused,
.mfx-date-picker .date-picker-popup .months-combo:focused {
    -fx-text-fill: red;
}
```

However, if I use:
```
#custom-date-picker .date-picker-popup .years-combo:focused,
#custom-date-picker .date-picker-popup .months-combo:focused{
    -fx-text-fill: red;
}
```

And then set id for my DatePicker - everything works.
![image](https://user-images.githubusercontent.com/29901577/152430056-93059936-6f99-424c-8b9a-2e6cf4dc2fa2.png)

Here's reproductable example:
**Main.java**
```
import io.github.palexdev.materialfx.controls.MFXDatePicker;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.Objects;

public class Main extends Application {
    @Override
    public void start(Stage stage) {
        HBox content = new HBox(100);
        content.getStylesheets().add(Objects.requireNonNull(getClass().getResource("main.css")).toExternalForm());

        MFXDatePicker date = new MFXDatePicker();

        MFXDatePicker dateCustom = new MFXDatePicker();
        dateCustom.setId("custom-date-picker");

        content.getChildren().addAll(date, dateCustom);
        Parent root = new Pane(content);
        Scene scene = new Scene(root);

        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**main.css**
```
.mfx-date-picker .date-picker-popup .years-combo:focused,
.mfx-date-picker .date-picker-popup .months-combo:focused {
    -fx-text-fill: red;
}

#custom-date-picker .date-picker-popup .years-combo:focused,
#custom-date-picker .date-picker-popup .months-combo:focused{
    -fx-text-fill: red;
}
```

![image](https://user-images.githubusercontent.com/29901577/152430683-acd4323c-64ec-48b0-9c33-8507a73bc536.png)
![image](https://user-images.githubusercontent.com/29901577/152430740-eacc3753-c4a3-4cc2-94c6-e33632c122c6.png)

I'm using:

- Windows 10
- JDK 17
- MaterialFX 11.13.0

I'm not sure if it's a bug or I am doing something wrong here, but the fact that the same path works using Id instead of class seems odd to me.
P.S. Some other properties also weren't changing. For example, ripple color of left-arrow and right-arrow.

**Comment by palexdev** [comment]
Thanks for sharing a minimal reproducible example, I'll look into it as soon as possible and let you know the cause of the issue

**Comment by palexdev** [comment]
@Laritello I can confirm the issue. An improvement is available on the staging branch.

The issue is that for some reason the ":focused" PseudoClass is ignored, yet I don't know why it works by setting the id.
Another workaround until the new minor version is out (couple days I think) is to change the CSS like this:
```css
.mfx-date-picker .date-picker-popup .years-combo .text-field:focused,
.mfx-date-picker .date-picker-popup .months-combo .text-field:focused {
    -fx-text-fill: red;
}
```


Just for "completion" the new minor version will allow to do this instead:
```css
.mfx-date-picker .date-picker-popup .years-combo:focus-within,
.mfx-date-picker .date-picker-popup .months-combo:focus-within {
    -fx-text-fill: red;
}
```

**Comment by Laritello** [comment]
Great! Thanks for quick response :)

**Comment by palexdev** [comment]
Fix available in the latest version
