### ISSUE TITLE
Cannot resolve method 'getCheckModel' in 'MFXCheckListView'

### ISSUE THREAD

**Issue by TheRedSpy15** [palexdev/MaterialFX#133]
I'm trying to use:
`@FXML public MFXCheckListView<String> listView;`

But having a problem here:
`listView.getCheckModel().getCheckedItems().addListener((ListChangeListener<String>) c -> System.out.println(listView.getCheckModel().getCheckedItems()));
`

keep getting:
`Cannot resolve method 'getCheckModel' in 'MFXCheckListView'`

everything else works with `listView` except when trying to `getCheckModel().`

Using version 11.13.0

**Comment by palexdev** [comment]
Is it an old project, I mean, did you update MaterialFX from an older version to 11.13.0?

I believe this is the case since now both list views rely on the same model
So for both list views it's `listView.getSelectionModel()`

**Comment by TheRedSpy15** [comment]
> Is it an old project, I mean, did you update MaterialFX from an older version to 11.13.0?
> 
> I believe this is the case since now both list views rely on the same model So for both list views it's `listView.getSelectionModel()`

Oh ok that makes sense. Its a new project but I find this documentation and was trying to follow it: https://controlsfx.github.io/javadoc/11.0.2/org.controlsfx.controls/org/controlsfx/control/CheckListView.html

of course now I'm seeing that this is for an older version

**Comment by palexdev** [comment]
Ah got it
MaterialFX has nothing to do with ControlsFX, very different programming styles, be sure to read controls documentation before using them, it can be very helpful 😉

To be honest, I should publish MaterialFX javadocs somewhere, and it's actually a high priority thing

**Comment by TheRedSpy15** [comment]
ha oh good god. I didn't even realize it was for controlsfx. I just googled it and that was what came up, guess I put too much faith in the google gods. Thank you for your time!
