### ISSUE TITLE
Installing MaterialFX to project causes No Toolkit Found

### ISSUE THREAD

**Issue by pablo67340** [palexdev/MaterialFX#138]

**Comment by palexdev** [comment]
Did you fix it?
It doesn't seem to be a problem related directly to MaterialFX but rather to JavaFX configuration  

Unfortunately I'm not an expert of Neatbens and Maven since I don't like them at all

**Comment by pablo67340** [comment]
I have not fixed it yet. If I remove MaterialFX from my dependencies, and remove the FXML I have converted over to MaterialFX Components, it builds and runs fine. When I add the dependency, something is thrown off.

**Comment by palexdev** [comment]
1) Can I take a look at the FXML?
2) Which controls are you using?
3) A minimal reproducible example would be great if possible, so I can reproduce the issue locally

**Comment by pablo67340** [comment]
So I restored my FXML to normal, No MaterialFX stuff in it. When I simply add MaterialFX to my pom.xml, and press run, it throws this error just by simply including this library. 

Here is my pom

https://pastebin.com/7BG9eWGY

This isolates the FXML out of the picture.

**Comment by pablo67340** [comment]
I have fixed the issue. It was a problem with my javafx SDK installation. Thank you so much for the help and fast replies.

**Comment by palexdev** [comment]
No problem, happy coding 😉
