### ISSUE TITLE
Request for MFXTextfield prompt text to disappear when Textfield is not empty and not on focus

### ISSUE THREAD

**Issue by georgioyammine** [palexdev/MaterialFX#14]
### not focused
![unfocused](https://user-images.githubusercontent.com/61707078/109431318-9f8ed180-7a0e-11eb-94ce-28507936fd0c.PNG)

### focused
![focused_](https://user-images.githubusercontent.com/61707078/109431383-f4cae300-7a0e-11eb-9eca-6c07d73435dd.PNG)

### focused
![expected_focused](https://user-images.githubusercontent.com/61707078/109431394-0e6c2a80-7a0f-11eb-9068-f8a9f3fed673.PNG)
_This image is taken from JFXTextfield._

Currently the prompt text disappear whenever the text field has focus but if it could be tied to the text property.

**Comment by palexdev** [comment]
To be honest I don't really like that behaviour but to fullfill your request I will add a BooleanProperty, hideOnFocus or something so anyone can choose the behaviour he likes the most.
Stay tuned I will push some fixes and minor changes in the next few days and then solve the issues

**Comment by georgioyammine** [comment]
Thank you for your efforts! I recently migrated from JDK 8 to 11 and found out about this library and it is awesome. Keep up the good work!

**Comment by palexdev** [comment]
@georgioyammine Thank you, knowing that my work is appreciated makes me happy 😄

About the issue I was reviewing the demo and I remembered that you can actually achieve that behavior with CSS.

![i1](https://user-images.githubusercontent.com/16880178/109645560-50a08380-7b57-11eb-8d4e-d20ae1506db0.png)
![i2](https://user-images.githubusercontent.com/16880178/109645562-526a4700-7b57-11eb-8df7-89cde917c3c4.png)

As you can see in the images when the textfields are focused the prompt text is still visible. What JavaFX does is to change the prompt text fill when it's focused to hide it, but you can easily change this behavior in CSS like this:

```
mfx-text-field:focused {
    -fx-prompt-text-fill: "color";
}
```

**Comment by georgioyammine** [comment]
This totally achieves the behavior I want. I didn't know it could simply be accomplished using a CSS rule.

Thank you for your time and suggestion.
