### ISSUE TITLE
MFXFilterComboBox, Chinese characters can't be input

### ISSUE THREAD

**Issue by Hamster5295** [palexdev/MaterialFX#140]
Before i start, i have to say that I **LOVE** the outstanding features very much! 😸 

However, i've found it **unable to text Chinese characters** into **the Search field of MFXFilterComboBox**. I'm not familiar with character  encodings so i can't figure out which part went wrong 
It's a critical problem since i'm using it to create a Chinese font selector, where users will have to search through a bunch of fonts

Hope there will be a fix soon 🍀 

By the way, There's no Chinese translation in the repo currently. If i want to contribute, what should I do? 🤔

**Comment by Hamster5295** [comment]
It's found that you CAN input these characters by copying and pasting them into the search box, but you CAN'T do it by typing with an input method (e.g. MSPY)

**Comment by Glavo** [comment]
I looked into this Issue and it's an issue on `MFXTextField`. When it's placed in a Popup (`javafx.stagePopup` or `MFXPopup`), you can't use an input method on it.

I'm a novice user of MaterialFX, still looking at the demo, haven't started using it yet. I'll take some time to keep track of the issue, but it won't necessarily fix it.

**Comment by Glavo** [comment]
After investigation, I found out that it is not MaterialFX causing the problem.

This is an issue on OpenJFX. When there is a `TextField` in the window, another `TextField` in the Popup that pops up on this window cannot be focused by the input method, and all input by the input method will appear in the `TextField` of the main window.

I will try to report the issue to OpenJFX.

**Comment by Glavo** [comment]
Here is a short reproducer. 

It's a window that contains `TextField`, and will pop up another `TextField` on the top left of the screen.

When you use the input method to input the upper left of the screen `TextField`, you will find that your input actually goes to the `TextField` in the main form.

```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.stage.Popup;
import javafx.stage.Stage;

public class JFXTest extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        var root = new VBox(new TextField());
        primaryStage.setScene(new Scene(root, 100, 100));
        primaryStage.show();

        Popup popup = new Popup();
        popup.getContent().add(new TextField("AAA"));
        popup.show(primaryStage, 0.0, 0.0);
    }

    public static void main(String[] args) {
        Application.launch(JFXTest.class, args);
    }
}
```

**Comment by Glavo** [comment]
For non-Asian users, this problem can also be reproduced using the Windows emoji emoji panel (Use the shortcut key Windows logo key and period  to open).

**Comment by Hamster5295** [comment]
That's of great help. Thank you! 😉

**Comment by Glavo** [comment]
> I'll try ro reproduce the issue and study a workaround if possible
> 
> Can't promise anything though. Sorry guys, it's been so tough lately, the university, MaterialFX a secret project for the JavaFX community that is talking a **a lot** of time, I'll do my best

Thank you for your great work. 

This is caused by an OpenJFX issue, which I've reported on the mailing list, and I think it should probably be resolved by someone at Oracle or Gluon.

**Comment by Glavo** [comment]
The issue has been reported to Oracle and tracked by JBS, see  [JDK-8234572](https://bugs.openjdk.java.net/browse/JDK-8234572).

**Comment by doublez-ten** [comment]
> Before i start, i have to say that I **LOVE** the outstanding features very much! 😸在我开始之前，我不得不说，我非常**喜欢**这些突出的功能！😸
> 
> However, i've found it **unable to text Chinese characters** into **the Search field of MFXFilterComboBox**. I'm not familiar with character encodings so i can't figure out which part went wrong然而，我发现它**无法文本中文字符**到**搜索领域的MFXFilterComboBox**。我对字符编码不熟悉，所以我不知道哪部分出错了 It's a critical problem since i'm using it to create a Chinese font selector, where users will have to search through a bunch of fonts这是一个关键的问题，因为我用它来创建一个中文字体选择器，用户将不得不通过一堆字体搜索
> 
> Hope there will be a fix soon 🍀希望很快会有一个解决方案。
> 
> By the way, There's no Chinese translation in the repo currently. If i want to contribute, what should I do? 🤔顺便说一句，目前回购中没有中文翻译。如果我想做贡献，我应该做什么？🤔

Use Pinyin to achieve the effect of search,such as:
```
filterCombo.setFilterFunction(new Function<String, Predicate<String>>() {
            @Override
            public Predicate<String> apply(String s) {
                return new Predicate<String>() {
                    @Override
                    public boolean test(String t) {
                        return StringUtils.containsIgnoreCase(PinyinUtil.getPinyin(t), s);
                    }
                };
            }
        });
```
