### ISSUE TITLE
Some components cannot be loaded

### ISSUE THREAD

**Issue by mat1911** [palexdev/MaterialFX#147]
When I load the library to the scene builder some components are not loaded. Below you can find a file with the JAR analysis report.
[errors.txt](https://github.com/palexdev/MaterialFX/files/8156538/errors.txt)

Similar problems occur when I try to add the components listed in the above file to a view manually (in code).

**Comment by mat1911** [comment]
I found a pinned issue with the answer to my problem. Sorry :)

**Comment by palexdev** [comment]
I was just writing that haha, glad you figured it out, happy coding ;)
