### ISSUE TITLE
The value of MFXDatePicker that is set before display will not be displayed correctly

### ISSUE THREAD

**Issue by Glavo** [palexdev/MaterialFX#172]
```java
var picker = new MFXDatePicker();
picker.setValue(LocalDate.now());

// ... Add picker to the window
```

In this case `MFXDatePicker` does not display the date text correctly.

The reason for this is that the logic associated with the text and value of the `MFXDatePicker` is located in the constructor of the `MFXDatePickerSkin`, so setting the value before creating the skin will not update the text content correctly.

**Comment by palexdev** [comment]
Fixed in version 11.13.5, easy fix an updateValue(...) call was needed during initialization
