### ISSUE TITLE
TextFormatter not working with the MFXTextFields

### ISSUE THREAD

**Issue by SaadSidd29** [palexdev/MaterialFX#175]
I was trying to implement a functionality of Numeric MFXTextfields, but somehow it wasn't updating. Was implemented perfectly with Normal JavaFX Textfields. I am using MFX 11.14.0-EA1

`Namemfx.setTextFormatter(new TextFormatter<>(change -> {
			if (change.getText().matches("[0-9]*")) {
				return change;
			}
			return null;
		}));`

**Comment by palexdev** [comment]
Hello, thanks for using MaterialFX!

Please don't use EA builds, I need them for a currently private project with experimental changes from the staging branch

The TextFormatter functionality should have been fixed in the latest stable release (11.13.5), check here #174

**Comment by SaadSidd29** [comment]
Thanks for the immediate response.
I will try that
