### ISSUE TITLE
MFXFilterComboBox doesn`t show the items

### ISSUE THREAD

**Issue by Homeshevchuk** [palexdev/MaterialFX#177]
FilterComboBox doesn`t show the items on first opening if the items list contains only 1 item.

**Comment by palexdev** [comment]
Can you share a minimal reproducible example please?

**Comment by Tech-Expert-Wizard** [comment]
It doesn't work for me either. Here's an MRE.
```java
import io.github.palexdev.materialfx.controls.MFXFilterComboBox;
import javafx.scene.layout.BorderPane;
import javafx.scene.Scene;
import javafx.stage.Stage;
public class Test extends javafx.application.Application {
    public void start(Stage stage) {
        MFXFilterComboBox box = new MFXFilterComboBox<String>();
        box.getItems().add("test");
        stage.setScene(new Scene(new BorderPane(box), 400, 400));
        stage.setTitle("Test");
        stage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by mahfoud09** [comment]
still not working if the ObservableList is empty and make a button event to add element to the combo it not showing

**Comment by infinite-dev22** [comment]
@mahfoud09 not sure how you are doing it(your code), I tried what you described and seems to work well.

![7y0jzu](https://github.com/palexdev/MaterialFX/assets/77667007/5171210d-ca5f-40c9-a201-9dd0daf38a9d)


```
public void start(Stage stage) throws Exception {

    ObservableList<String> comboItemsList = FXCollections.observableArrayList(
            "Jane", "Mary", "Mark", "Jon", "Mane");

    MFXFilterComboBox<String> namesCombo = new MFXFilterComboBox<>();

    Button setComboItemsBtn = new Button("Add Items");
    setComboItemsBtn.setOnAction(event -> namesCombo.setItems(comboItemsList));

    VBox root = new VBox(setComboItemsBtn, namesCombo);
    root.setPadding(new Insets(20));
    root.setAlignment(Pos.TOP_CENTER);
    root.setSpacing(50);

    Scene scene = new Scene(root, 400, 300);
    MFXThemeManager.addOn(scene, Themes.DEFAULT, Themes.LEGACY);
    io.github.palexdev.mfxcomponents.theming.MaterialThemes.PURPLE_LIGHT.applyOn(scene);

    stage.setScene(scene);
    stage.show();
}
```

**Comment by mahfoud09** [comment]
@infinite-dev22 
try like this with empty observableList and add one by one 
ObservableList<String> comboItemsList = FXCollections.observableArrayList();
setComboItemsBtn.setOnAction(event -> namesCombo..getItems().add("Mane"));

**Comment by infinite-dev22** [comment]
@mahfoud09 still works like a gem. Though now declaring an ```ObservableList``` isn't necessary.
![ezgif-1-faba17b187](https://github.com/palexdev/MaterialFX/assets/77667007/268e8f0a-fb4e-42d9-b97a-827fb2cf0262)

I think it would be best if you shared your code of an MRE that replicates your error or bug.

**Comment by mahfoud09** [comment]
@infinite-dev22
but i want to binding an empty observableList to the FilterCombo and adding one by one on Form ... its not working

**Comment by infinite-dev22** [comment]
Use this... not the best way though but gets the needed functionality as per your description.

```
public void start(Stage stage) throws Exception {
    ObservableList<String> comboItemsList = FXCollections.observableArrayList();

    ...

    setComboItemsBtn.setOnAction(event -> {
        comboItemsList.add(textField.getText());
        namesCombo.setItems(comboItemsList);
    });

    ...
}
```
