### ISSUE TITLE
MFXGenericDialog usage

### ISSUE THREAD

**Issue by SaadSidd29** [palexdev/MaterialFX#181]
Hi @palexdev 

I am not able to use this feature. 
I have gone through the example demo also.
Can you help me implement this ... After some action is performed I need to show Confirmation to user

**Comment by Tech-Expert-Wizard** [comment]
@SaadSidd29 You can simply instantiate the class `io.github.palexdev.materialfx.dialogs.MFXGenericDialog`. The Javadoc is [here](https://javadoc.io/static/io.github.palexdev/materialfx/11.13.5/MaterialFX/io/github/palexdev/materialfx/dialogs/MFXGenericDialog.html).

**Comment by palexdev** [comment]
> @SaadSidd29 You can simply instantiate the class `io.github.palexdev.materialfx.dialogs.MFXGenericDialog`. The Javadoc is [here](https://javadoc.io/static/io.github.palexdev/materialfx/11.13.5/MaterialFX/io/github/palexdev/materialfx/dialogs/MFXGenericDialog.html). @palexdev I think this can be closed.

Thanks 🙏

Don't forget to read the Javadocs guys

**Comment by SaadSidd29** [comment]
I tried but it's not working.

`MFXGenericDialog dialog = new MFXGenericDialog("Header","Test");`
