### ISSUE TITLE
TextField doesn't accept TextFormatter

### ISSUE THREAD

**Issue by MohamadShaheen** [palexdev/MaterialFX#182]
I've been trying a lot lately to let the MFXTextField accept only numbers, Meaning when trying to write a letter in the TextField it will not accept or show it.

After many tries and a lot of time, it emerged to be the MFXTextField problem. When I tried all the solutions on a regular TextField it passed and worked perfectly but non of them worked on MFXTextField.

I hope for a fix as soon as possible.

All the best.

**Comment by mahfoud09** [comment]
use delegateSetTextFormatter(yourmfxtextfield);

**Comment by MohamadShaheen** [comment]
Thanks it worked.

**Comment by MohamadShaheen** [comment]
Thanks it worked.

**Comment by MohamadShaheen** [comment]
Thanks, it worked.

**Comment by MohamadShaheen** [comment]
Thanks, it worked.
