### ISSUE TITLE
How to create round material button with images instead of text?

### ISSUE THREAD

**Issue by omegaui** [palexdev/MaterialFX#192]
![Screenshot from 2022-04-29 16-05-59](https://user-images.githubusercontent.com/73544069/165929182-a5fcd7b3-3453-4dc4-942d-edaeedc60c44.png)

I am writing a code editor with materialFX.

I want to create a same control as the filter button in the above image.
Is there some other control than `MFXButton` to achieve this behaviour?

**Comment by omegaui** [comment]
Got it!
Actually, I am a beginner in JavaFX

**Comment by omegaui** [comment]
@palexdev 
Thanks a lot.
I was using the `-fx-background-radius` property.
But this seems more appealing to me.

**Comment by omegaui** [comment]
@palexdev 
Can you please help me out, I am just starting out with JavaFX?

When using the above code, I am getting the following error ...
![Screenshot from 2022-05-01 14-13-23](https://user-images.githubusercontent.com/73544069/166138666-798ed820-4600-4391-9685-19b668a7a542.png)

These are my modules and I am using javafx 17 ...
![Screenshot from 2022-05-01 14-12-30](https://user-images.githubusercontent.com/73544069/166138686-afedb6ff-faa4-43af-82b9-783cfcc372f3.png)

Although this probably points either
- I am missing some dependency
- **Or** The Library utilizes a non-modular version of the JDK.

**Comment by M-K-Al** [comment]
I would love to help you out!
Can you plseae copy the whole exception?
But from the fist look have you added _fontawesomefx_? I don't see it in your models list.

**Comment by omegaui** [comment]
Thanks for taking a step to help!

But I figured it out, I switched to [icons8](https://icons8.com).

**Comment by omegaui** [comment]
My IDE is built different
