### ISSUE TITLE
MFXTableView#setFooterVisible dosen't work

### ISSUE THREAD

**Issue by M-K-Al** [palexdev/MaterialFX#193]
Hi, i'm trying to remove the filter icons from a `MFXPaginatedTableView ` but `MFXTableView#setFooterVisible` doesn't seem to change anything. (if that even supposed to remove them)

**Comment by palexdev** [comment]
Yes it is supposed to remove the bottom bar from the tables, can you share a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.)?
