### ISSUE TITLE
Material Design JavaFX Skin-Only implementation

### ISSUE THREAD

**Issue by DJViking** [palexdev/MaterialFX#195]
This is probably a major rewrite, but something I think should be done.
This MaterialFX should just have its own Skins, instead of having its own Controls.
Just like JMetro has done for Fluent Design. Both JFoenix and MaterialFX have its own components for each JavaFX control. While JMetro uses JavaFX own components, but just overrides their Skin.

It would make it much easier to switch design library. Right now we are using JFoenix, and would need to rewrite all JFX Controls and JFX CSS over to MFX Controls and MFX CSS.

**Comment by palexdev** [comment]
Nope
MaterialFX is not just a re-style nor just a re-skin
I started this project with the intention of bringing my own controls and skin, MaterialFX is intended to be much more that that
