### ISSUE TITLE
Request for MFXDatePicker

### ISSUE THREAD

**Issue by Alex50505** [palexdev/MaterialFX#2]
Hi, I would like to request a date picker for MaterialFX. The `JFXDatePicker` that I used before JDK 11 worked fine, until I started using JDK 11 and JavaFX 11. Now I need to use an `add-opens` VM option and [multiple ones are needed for it to work](https://github.com/jfoenixadmin/JFoenix/issues/889). However, my favorite IDE, NetBeans, doesn't allow me to have multiple `add-opens`, so could you please add a `MFXDatePicker`? Thanks!

**Comment by palexdev** [comment]
Testo di origine
Yep I'm well aware of workarounds needed to make JFoenix work, that's why I started this project.
I was going to implement MFXTreeView and MFXTableView next but I will give a higher priority to MFXDatePicker

**Comment by palexdev** [comment]
@Alex50505 Hey just wanted to let you know MFXDatePicker is almost there. 
In the next few days I will complete it.
Also, maybe I won't publish it in the main branch but on a new dev branch.
Would you like to test it out so that I can safely publish it in the main branch?
