### ISSUE TITLE
Linear gradient causes "class javafx.scene.paint.LinearGradient cannot be cast to class javafx.scene.paint.Color"

### ISSUE THREAD

**Issue by DBChoco** [palexdev/MaterialFX#202]
**Describe the bug**
When using this
`-common-gradient: linear-gradient(to right bottom, #0af6bb, #420aa4);`
with this
```
.mfx-checkbox, .mfx-radio-button{
    -mfx-main: -common-gradient;
}
```
I get this: 
```
May 17, 2022 12:24:03 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class javafx.scene.paint.LinearGradient cannot be cast to class javafx.scene.paint.Color (javafx.scene.paint.LinearGradient and javafx.scene.paint.Color are in module javafx.graphics@18-ea of loader 'app')' while converting value for '-mfx-ripple-color' from rule '*.mfx-checkbox *.ripple-container *.mfx-ripple-generator' in stylesheet jar:file:///home/XXXXXX/.m2/repository/io/github/palexdev/materialfx/11.13.5/materialfx-11.13.5.jar!/io/github/palexdev/materialfx/css/MFXCheckBox.css
```

**[MRE](https://bit.ly/3k5gTJf)(Minimal Reproducible Example)**
Project is [here](https://github.com/DBChoco/Salawat)

**To Reproduce**
1. Just run the Main, then go to the "Settings" scene, where all the checkboxes are.

**Screenshots**
The css does work, it just shows a lot of error messages 
![](https://i.imgur.com/ppMRRHN.png)

**Comment by palexdev** [comment]
I'll check this asap

**Comment by palexdev** [comment]
@DBChoco found the issue
Both MFXCheckbox and MFXRadioButton have something like this `-mfx-ripple-color: derive(-mfx-main, percentage);` to make the ripple color depend on the main color
The CSS `derive(...)` function however cannot operate on gradients, so if you don't override that rule too you'll see the errors and the ripple color will fallback to gray
