### ISSUE TITLE
MFXSlider doesnt enable starting drag action from the track

### ISSUE THREAD

**Issue by Tengyyy** [palexdev/MaterialFX#214]
Default JavaFX slider allows you to press and drag anywhere on the slider track and the slider will adjust. The MFXSlider only allows you to click on a spot on the track and the slider thumb will move there but you can't start a drag from the track. Not sure if this is intentional or not but in my opinion this is a bad design practice.

**Comment by palexdev** [comment]
This should not happen
In fact if you check the gif about the Sliders on the REAME you can see that I'm dragging the thumb

What version of MaterialFX are you using?
Can you share a MRE?

**Comment by Tengyyy** [comment]
Made a clip to show what I mean.
On the default JavaFX slider you can start a drag action not only from the thumb but the bar/track itself. With the MFXSlider this does not seem to be possible.

https://user-images.githubusercontent.com/69690923/180977919-f035b3d6-4958-4ce2-820d-0fec069d9f80.mp4

**Comment by palexdev** [comment]
Ah yes it's not possible
I don't think it's a great loss though and I would rather avoid that behavior to be honest
