### ISSUE TITLE
MFXTextField based controls minor issues

### ISSUE THREAD

**Issue by gilad4** [palexdev/MaterialFX#220]
Playing around with the input controls I have noticed some minor issues:

- For all MFXTextField based controls
Pressing TAB to focus traverse between controls works correctly, but pressing Shift+TAB to reverse does not work.
This can be fixed by setting 'setFocusTraversable' to **false** and leaving the value for the boundField as **true**.
This should probably be their default values.

- MFXTextField / MFXPasswordField context menu
The context menu items Delete / Undo / Redo, do not work since they are not referring to the inner boundText.
The shortcut for Delete (Ctrl+D) as shown in the accelerator hint does not work either - not sure if there an event handler for this somewhere but I did not see any.
![image](https://user-images.githubusercontent.com/19804616/174817086-32119b07-e1df-4bc3-a35d-571278cd1e83.png)

- MFXPasswordField
The properties allowCutProperty/allowCopyProperty/allowPasteProperty are not taking into account when pressing the relevant shortcut keys, so basically user is able to cut/copy/paste even when properties are set to false

Can see my commit which fixes these issues. https://github.com/gilad4/MaterialFX/commit/8e620dad61139d3f26fbf4caf50e66fa1ebd5f42
Tell me in case you want a PR

**Comment by gilad4** [comment]
@Kaly380 not relevant to this issue but you can try this:
```
myMfxTextField.delegateSetTextFormatter(new TextFormatter<>(change -> {
  change.setText(change.getText().toUpperCase());
  return change;
}));
```

**Comment by gilad4** [comment]
@palexdev would be also nice to fix these for your next minor release as they are pretty easy to fix

**Comment by palexdev** [comment]
@gilad4 ah sorry, you are right
As @stefanofornari suggested my in a discussion recently I merged all the open PRs before working in my next big release
Sorry I totally forgot to check the issues

**Comment by palexdev** [comment]
@gilad4 if you can send a PR whenever you can, no pressure
I'll merge it and release a new version

**Comment by gilad4** [comment]
@palexdev added a PR

**Comment by palexdev** [comment]
Thank you, I'm not at home right now, I'll merge it  asap
