### ISSUE TITLE
how are you plane use setSelection method?

### ISSUE THREAD

**Issue by deni5n** [palexdev/MaterialFX#222]
I will need to render the selected row in "MFXTableView" when the user presses the right mouse button to display the context menu (by default, the row is not selected when the user presses the right mouse button). I see the method:

``` java
table.getSelectionModel().setSelection()
```

but that i can send him a parameter? 
can you provide an example?

**Comment by deni5n** [comment]
``` java
MFXTableColumn<User> idColumn = new MFXTableColumn<>("Id", true, Comparator.comparing(User::getId));
        idColumn.setRowCellFactory(user -> new MFXTableRowCell<>(User::getId) {{
            setOnMouseClicked(mouseEvent -> {
                ObservableMap<Integer, User> map = FXCollections.observableHashMap();
                int i = users.indexOf(user);
                map.put(i, user);
                table.getSelectionModel().setSelection(map);
                setContextMenu(menu(user));
            });
        }});
```

but context menu is not showing. perhaps the update is not synchronous and the context menu is overwritten?

**Comment by palexdev** [comment]
There is no context menu by default plus there's a much simpler way to allow selection with the right mouse button

For both you need a custom row you can extend MFXTableRow as it already offers everything you need 
Check both the documentation and the src code

**Comment by deni5n** [comment]
[palexdev](https://github.com/palexdev) I don't understand? what is the easier way? I gave an example - it doesn't work that way. the line is highlighted, but the context menu does not appear. I have to press the right button again

**Comment by deni5n** [comment]
if you register a factory and listen to mouse events in it, then they don’t come at all ((



``` java
table.setTableRowFactory(resource -> {
            Row<User> row = new Row<>(table, resource);
            row.setOnMouseClicked(event -> {
                row.updateSelection(event);  // <-----  not called
            });
            return row;
        });
```
