### ISSUE TITLE
MFXDialog displaced at first

### ISSUE THREAD

**Issue by stefanofornari** [palexdev/MaterialFX#227]
**Describe the bug**
It seems MFXDialog is displaced at first, and then suddenly moved to its final position. I am able to reproduce it consistently with the demo application. After the first time, it looks like the effect is much less visible. But moving the window and showing the dialog again, most of the time results in the displacement effect.

See the attached screencast ([here the link](https://zefiro.me/share/4v9NeWxNF7e4nQf6) in case github does not play it)

https://user-images.githubusercontent.com/43138/182414948-a67be15a-fbdf-4178-a447-cdbdabe69da5.mp4

.

**Comment by palexdev** [comment]
On Github the video doesn't work, and it doesn't even work at the link you shared

**Comment by palexdev** [comment]
I did download it but it was saying unsupported codec or something like that

**Comment by stefanofornari** [comment]
Ok, now you should see it. Let me know if you need any more info.

**Comment by palexdev** [comment]
@stefanofornari  I cannot reproduce it for some reason

https://user-images.githubusercontent.com/16880178/225305290-61ad7d9a-199e-448c-9183-23276ebd2d87.mp4

**Comment by stefanofornari** [comment]
I will try again with the latest version, but the key was to move the main window. Have you tried it as well?

**Comment by palexdev** [comment]
I just tried to move the window too but I see no displacement
Could it be an hardware related issue? Maybe my PC is so fast that displacement occurs but I can't percieve it

**Comment by stefanofornari** [comment]
I can still reproduce with the latest demo release:

1. open the demo and move the window bottom left
2. Click on Dialogs and then press Info; close the popup.
3. move the demo window top right and press Info

I see the popup displayed in the previous position then moved to the center of the main window.

It may be my PC performance, as it is an old PC. If you are not able to reproduce it, I will try to have a look; it smells a bug between positioning and displaying the popup, maybe just noticeable on low-end PCs.

**Comment by stefanofornari** [comment]
I have tried on my laptop which is quite modern and the effect is not noticeable. It is still Linux, therefore I would exclude it is due to the SO. I will looking into the code.

**Comment by palexdev** [comment]
I thought so
Maybe I have an a "concept" more than an actual idea
It could be a solution try finding a way of not showing the dialog until the very final position is computed
The positioning algorithm and the skin may need to be reviewed though
