### ISSUE TITLE
Do not make FXML a required module

### ISSUE THREAD

**Issue by rnayabed** [palexdev/MaterialFX#234]
**Is your feature request related to a problem? Please describe.**
I am working on a JavaFX project that does not make use of FXML and uses JavaFX via standard Java API.

**Describe the solution you'd like**
The components that require the FXML module could be moved to a seperate module to allow users to access core MaterialFX controls without having to load FXML module.

**Comment by palexdev** [comment]
Just because you are not using FXML doesn't mean that other people is not using it
Also we are talking about removing a module that (at least for the Linux package) occupies around 130KB of space
To be honest it's not worth the hassle
