### ISSUE TITLE
How to set our own TextFormatter on MFXTextField

### ISSUE THREAD

**Issue by chuckdu21** [palexdev/MaterialFX#247]
Hi,
I'd like to set my own TextFormatter on a MFXTextField but i get this error:
`formatter is already used in other control `

I tried to unbind the textformatter, even on the boundField but my TextFormatter won't set. (I tried the same textformatter on a default TextField and it's working).

Here's a sample of my code:
```

public class MFXDateTimeField extends MFXTextField {
    UnaryOperator<TextFormatter.Change> filter;

    public MFXDateTimeField() {
        super();
        this.filter = c -> {
            if (c.isAdded()) {
                c.setRange(c.getRangeStart(),
                        Math.min(c.getControlText().length(), c.getRangeStart() + c.getText().length()));
            }
            return c;
        };
        this.setTextFormatter(new TextFormatter<Object>(filter));
```

How can i "force" to set my TextFormatter or something like this ?

**Comment by mahfoud09** [comment]
this.delegateSetTextFormatter(new TextFormatter<Object>(filter));

**Comment by mahfoud09** [comment]
What the version of *Materielfx* you use

**Comment by chuckdu21** [comment]
I deleted my answer because i was on 11.13.0^^
I just did the update and i found the method. Now it's working ! thx

But another issue: getPositionCaret always returns 0
