### ISSUE TITLE
Custom TableView

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#25]
Maybe I am missing something but there is any option to add customized column with buttons ?

**Comment by palexdev** [comment]
Unlike the rows there's no factory for the column cells. The column cell is just a label with an icon for sorting.
The only way would be to extend MFXTableColumnCell and provide a custom skin by extending MFXTableColumnCellSkin and then overriding the createDefaultSkin method

**Comment by lizhongyue248** [comment]
How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.

```
    val actionCell = MFXTableColumnCell<Data>("action")
    actionCell.setRowCellFactory {
      // I don't know how to use...
      // return@setRowCellFactory MFXTableRowCell(it.date)
    }
```

Thanks.

**Comment by palexdev** [comment]
> How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> 
> ```
>     val actionCell = MFXTableColumnCell<Data>("action")
>     actionCell.setRowCellFactory {
>       // I don't know how to use...
>       // return@setRowCellFactory MFXTableRowCell(it.date)
>     }
> ```
> 
> Thanks.
```

        MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
        columnCell.setRowCellFactory(data -> {
            MFXTableRowCell rowCell = new MFXTableRowCell("Text");
            MFXButton bt = new MFXButton("Button");
            rowCell.setGraphic(bt);
            return rowCell;
        });
```

I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method

**Comment by lizhongyue248** [comment]
> > How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> > ```
> >     val actionCell = MFXTableColumnCell<Data>("action")
> >     actionCell.setRowCellFactory {
> >       // I don't know how to use...
> >       // return@setRowCellFactory MFXTableRowCell(it.date)
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks.
> 
> ```
> 
>         MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
>         columnCell.setRowCellFactory(data -> {
>             MFXTableRowCell rowCell = new MFXTableRowCell("Text");
>             MFXButton bt = new MFXButton("Button");
>             rowCell.setGraphic(bt);
>             return rowCell;
>         });
> ```
> 
> I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method

Yeah, it works. But these bottons have not any actions and i can't click them. They're just graphics.

I think that we need a guide of `MaterialFX`.... （┭┮﹏┭┮）

**Comment by palexdev** [comment]
> > > How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> > > ```
> > >     val actionCell = MFXTableColumnCell<Data>("action")
> > >     actionCell.setRowCellFactory {
> > >       // I don't know how to use...
> > >       // return@setRowCellFactory MFXTableRowCell(it.date)
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Thanks.
> > 
> > ```
> > 
> >         MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
> >         columnCell.setRowCellFactory(data -> {
> >             MFXTableRowCell rowCell = new MFXTableRowCell("Text");
> >             MFXButton bt = new MFXButton("Button");
> >             rowCell.setGraphic(bt);
> >             return rowCell;
> >         });
> > ```
> > 
> > I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method
> 
> Yeah, it works. But these bottons have not any actions and i can't click them. They're just graphics.
> 
> I think that we need a guide of `MaterialFX`.... （┭┮﹏┭┮）
> 

Did you add and event hadler or filter to the button?

**Comment by lizhongyue248** [comment]
> > > > How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> > > > ```
> > > >     val actionCell = MFXTableColumnCell<Data>("action")
> > > >     actionCell.setRowCellFactory {
> > > >       // I don't know how to use...
> > > >       // return@setRowCellFactory MFXTableRowCell(it.date)
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Thanks.
> > > 
> > > 
> > > ```
> > > 
> > >         MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
> > >         columnCell.setRowCellFactory(data -> {
> > >             MFXTableRowCell rowCell = new MFXTableRowCell("Text");
> > >             MFXButton bt = new MFXButton("Button");
> > >             rowCell.setGraphic(bt);
> > >             return rowCell;
> > >         });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method
> > 
> > 
> > Yeah, it works. But these bottons have not any actions and i can't click them. They're just graphics.
> > I think that we need a guide of `MaterialFX`.... （┭┮﹏┭┮）
> 
> Did you add and event hadler or filter to the button?

Of course. It will select this row when I click the botton.

```kotlin
    val actionCell = MFXTableColumnCell<Data>("Action")
    actionCell.setRowCellFactory {
      val rowCell = MFXTableRowCell(it.name)
      val mfxButton = MFXButton("Delete")
      rowCell.graphic = mfxButton
      mfxButton.onMouseClicked = EventHandler {
        println("test")
      }
      return@setRowCellFactory rowCell
    }
```

**Comment by palexdev** [comment]
> > > > > How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> > > > > ```
> > > > >     val actionCell = MFXTableColumnCell<Data>("action")
> > > > >     actionCell.setRowCellFactory {
> > > > >       // I don't know how to use...
> > > > >       // return@setRowCellFactory MFXTableRowCell(it.date)
> > > > >     }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Thanks.
> > > > 
> > > > 
> > > > ```
> > > > 
> > > >         MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
> > > >         columnCell.setRowCellFactory(data -> {
> > > >             MFXTableRowCell rowCell = new MFXTableRowCell("Text");
> > > >             MFXButton bt = new MFXButton("Button");
> > > >             rowCell.setGraphic(bt);
> > > >             return rowCell;
> > > >         });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method
> > > 
> > > 
> > > Yeah, it works. But these bottons have not any actions and i can't click them. They're just graphics.
> > > I think that we need a guide of `MaterialFX`.... （┭┮﹏┭┮）
> > 
> > Did you add and event hadler or filter to the button?
> 
> Of course. It will select this row when I click the botton.
> 
> ```kotlin
>     val actionCell = MFXTableColumnCell<Data>("Action")
>     actionCell.setRowCellFactory {
>       val rowCell = MFXTableRowCell(it.name)
>       val mfxButton = MFXButton("Delete")
>       rowCell.graphic = mfxButton
>       mfxButton.onMouseClicked = EventHandler {
>         println("test")
>       }
>       return@setRowCellFactory rowCell
>     }
> ```

Ok this is normal, try to use and event filter, you can also consume the event in that filter if you don't want the row to be selected

**Comment by lizhongyue248** [comment]
> > > > > > How can I customize the row cell？I want to add `MFXButton` to cell. But `MFXTableRowCell` param is `String`.
> > > > > > ```
> > > > > >     val actionCell = MFXTableColumnCell<Data>("action")
> > > > > >     actionCell.setRowCellFactory {
> > > > > >       // I don't know how to use...
> > > > > >       // return@setRowCellFactory MFXTableRowCell(it.date)
> > > > > >     }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Thanks.
> > > > > 
> > > > > 
> > > > > ```
> > > > > 
> > > > >         MFXTableColumnCell<Data> columnCell = new MFXTableColumnCell<Data>();
> > > > >         columnCell.setRowCellFactory(data -> {
> > > > >             MFXTableRowCell rowCell = new MFXTableRowCell("Text");
> > > > >             MFXButton bt = new MFXButton("Button");
> > > > >             rowCell.setGraphic(bt);
> > > > >             return rowCell;
> > > > >         });
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > I didn't test it, but that should be the right way to do it. Row cells extend Label, so you can still use the setGraphic() method
> > > > 
> > > > 
> > > > Yeah, it works. But these bottons have not any actions and i can't click them. They're just graphics.
> > > > I think that we need a guide of `MaterialFX`.... （┭┮﹏┭┮）
> > > 
> > > 
> > > Did you add and event hadler or filter to the button?
> > 
> > 
> > Of course. It will select this row when I click the botton.
> > ```kotlin
> >     val actionCell = MFXTableColumnCell<Data>("Action")
> >     actionCell.setRowCellFactory {
> >       val rowCell = MFXTableRowCell(it.name)
> >       val mfxButton = MFXButton("Delete")
> >       rowCell.graphic = mfxButton
> >       mfxButton.onMouseClicked = EventHandler {
> >         println("test")
> >       }
> >       return@setRowCellFactory rowCell
> >     }
> > ```
> 
> Ok this is normal, try to use an event filter, you can also consume the event in that filter if you don't want the row to be selected

I'm sorry...... I can't understand your means.

```kotlin
    val table = MFXTableView<Data>()
    val actionCell = MFXTableColumnCell<Data>("Action")
    actionCell.setRowCellFactory {
      val rowCell = MFXTableRowCell(it.name)
      val mfxButton = MFXButton("Delete")
      mfxButton.addEventFilter(MouseEvent.ANY) { event -> print("button ${event.eventType}”) }
      rowCell.graphic = mfxButton
      return@setRowCellFactory rowCell
    }
    actionCell.addEventFilter(MouseEvent.ANY) { println("action ${it.eventType}") }
    table.addEventFilter(MouseEvent.ANY) { print("table ${it.eventType}") }
```

The output when I click `Delete` button:

```
table MOUSE_ENTERED
table MOUSE_ENTERED_TARGET
table MOUSE_MOVED
table MOUSE_PRESSED
table MOUSE_RELEASED
table MOUSE_CLICKED
table MOUSE_MOVED
table MOUSE_EXITED_TARGET
```

All events are about tables, not buttons.

**Comment by palexdev** [comment]
Yes you are right I just tested it, and it doesn't work
But I have found the issue. In the table skin the cells are set to be transparent to mouse events, to be honest I don't remember why.
Don't worry, the table view control will be reviewed entirely. As a temporary workaround you can do this:
```
        MFXTableColumnCell<FilterablePerson> ageColumn = new MFXTableColumnCell<>("Age", Comparator.comparing(FilterablePerson::getAge));
        ageColumn.setRowCellFactory(person -> new MFXTableRowCell(person.ageProperty().asString()) {
            {
                setAlignment(Pos.CENTER_RIGHT);

                MFXButton button = new MFXButton("TestButton");
                button.addEventFilter(MouseEvent.MOUSE_PRESSED, event -> System.out.println("PRESSED!!!"));
                setGraphic(button);

                mouseTransparentProperty().addListener((observable, oldValue, newValue) -> {
                    System.out.println(newValue);
                    if (newValue) {
                        setMouseTransparent(false);
                    }
                });
            }
        });

```

This is a piece of code from the demo which I modified to test the issue. The important part there is the listener.
Add a listener to the mouseTransparentProperty of the row, when it is true (if newValue) you set it to false

**Comment by lizhongyue248** [comment]
> Yes you are right I just tested it, and it doesn't work
> But I have found the issue. In the table skin the cells are set to be transparent to mouse events, to be honest I don't remember why.
> Don't worry, the table view control will be reviewed entirely. As a temporary workaround you can do this:
> 
> ```
>         MFXTableColumnCell<FilterablePerson> ageColumn = new MFXTableColumnCell<>("Age", Comparator.comparing(FilterablePerson::getAge));
>         ageColumn.setRowCellFactory(person -> new MFXTableRowCell(person.ageProperty().asString()) {
>             {
>                 setAlignment(Pos.CENTER_RIGHT);
> 
>                 MFXButton button = new MFXButton("TestButton");
>                 button.addEventFilter(MouseEvent.MOUSE_PRESSED, event -> System.out.println("PRESSED!!!"));
>                 setGraphic(button);
> 
>                 mouseTransparentProperty().addListener((observable, oldValue, newValue) -> {
>                     System.out.println(newValue);
>                     if (newValue) {
>                         setMouseTransparent(false);
>                     }
>                 });
>             }
>         });
> ```
> 
> This is a piece of code from the demo which I modified to test the issue. The important part there is the listener.
> Add a listener to the mouseTransparentProperty of the row, when it is true (if newValue) you set it to false

Oh, it works. But this way is complex for many buttons in the cell.

Hope to be fixed in the next release.    (๑•̀ㅂ•́)و✧👍

Thanks~~！

**Comment by palexdev** [comment]
I probably didn't think about adding nodes to cells because it's not a great idea, it depends
If the node is a little icon no problem, but more than one, or bigger nodes, better avoid that
The user interface should be as clean as possible, in fact if you need to add more than one button/actions you could use a context menu instead

Anyway I'll rework it ;)

**Comment by palexdev** [comment]
Improved in latest release
