### ISSUE TITLE
MFXDatePicker

### ISSUE THREAD

**Issue by PLEUTOSEEK** [palexdev/MaterialFX#259]
I would like to ask whether MFXDatePicker could implement a date range limit function, which let the user only able to select defined date range values.

Millions of thanks to author(s).

**Comment by PLEUTOSEEK** [comment]
`        this.dtDatePicker.setCellFactory(new Function<>() {
            @Override
            public MFXDateCell apply(LocalDate t) {
                return new MFXDateCell(dtDatePicker, t) {
                    @Override
                    public void updateItem(LocalDate item) {
                        super.updateItem(item);

                        if (item.isBefore(LocalDate.now())) {
                            setDisable(true);
                        } else {
                            setDisable(false);
                        }
                    }
                };

            }
        });`

Hey, I found the way to apply it, thank you and I will close this issue.

**Comment by PLEUTOSEEK** [comment]
```  
this.dtDatePicker.setCellFactory(new Function<>() {
            @Override
            public MFXDateCell apply(LocalDate t) {
                return new MFXDateCell(dtDatePicker, t) {
                    @Override
                    public void updateItem(LocalDate item) {
                        super.updateItem(item);

                        if (item.isBefore(LocalDate.now())) {
                            setDisable(true);
                        } else {
                            setDisable(false);
                        }
                    }
                };

            }
        });
```

**Comment by palexdev** [comment]
Glad to see you found a way
Keeping this in mind as an improvement for the future, added to the Improvements list as TBD
