### ISSUE TITLE
MFXScrollPane: Modify scrolling speed

### ISSUE THREAD

**Issue by chuckdu21** [palexdev/MaterialFX#260]
Hi,

I try to modify the scrolling speed of a MFXScrollPane.
I tried: 
`scrollPane.lookup(".scroll-bar:vertical")` to get scroll bar but return null.

Is there a way to do it or it's not implemented wait ?

**Comment by palexdev** [comment]
Hello, which version are you using?

**Comment by chuckdu21** [comment]
11.13.5

**Comment by palexdev** [comment]
I'm not sure if that lookup is valid  
Try using ``lookupAll(.scroll-bar)````  
You will get a Set of nodes, iterate over it, cast to ScrollBar and then check if the orientation is the one you need  
Also, make sure the node has been laid out is a scene so that its skin is not null (for that you could also use NodeUtils)

**Comment by chuckdu21** [comment]
Does not work, the set is empty..

**Comment by chuckdu21** [comment]
I tried to get the children. the list is also empty.

**Comment by chuckdu21** [comment]
Ok it's working I just put this line of code in a place where scrollbar is not created yet in the MFXScrollPane.
blockincrement is 0.9
unitincrement is 0.1
How can i increase the speed of scrolling ?

**Comment by palexdev** [comment]
As of 11.3.5 MFXScrollPane is just a simple extension of ScrollPane to fix a bug that causes the content to be blurry

That being said Google is your friend: [StackOverflow](https://stackoverflow.com/questions/32739269/javafx-how-do-i-change-the-amount-by-which-scrollpane-scrolls)
