### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by SudoDios** [palexdev/MaterialFX#263]
Hi.
Very nice library.
Can you add RTL support to TextField (Or autodetect rtl and ltr languages) ?

**Comment by palexdev** [comment]
Thanks!

Such feature should already be covered by JavaFX with the node orientation, see [JavaDoc](https://docs.oracle.com/javase/8/javafx/api/javafx/geometry/NodeOrientation.html) and [StackOverflow](https://stackoverflow.com/questions/33604907/javafx-8-rtl-support)

**Comment by SudoDios** [comment]
Thank you for responding so quickly 😍.
I meant auto direction in TextField

**Comment by palexdev** [comment]
Ah I see you meant an auto detection system
Unfortunately to be honest I have no interest in that
The feature itself should not bee too much hard to implement but maybe setting it manually is a better idea to have more control on all the nodes separately
