### ISSUE TITLE
MFXPasswordField doesn't follow language settings

### ISSUE THREAD

**Issue by zxzxy** [palexdev/MaterialFX#265]
The MFXPasswordField component doesn't follow the language settings, while other works just fine.

I did this to set the language to Chinese:
```java
I18N.setLanguage(Language.SIMPLIFIED_CHINESE);
```
And for the MFXTextField, it works fine like this
![image](https://user-images.githubusercontent.com/73475219/205922739-cda017fc-5da0-49db-a81e-9f3c950b8071.png)
But as for the MFXPasswordField, it won't work
![image](https://user-images.githubusercontent.com/73475219/205922725-4c7623a8-bdf5-43dc-ba4a-36ee5798d9b6.png)

I guess it is because the MFXPasswordField uses hard-coded text, while the MFXTextField reads the config
https://github.com/palexdev/MaterialFX/blob/e4573631d7f18fe4febc099eb2a9443719b3b0f8/materialfx/src/main/java/io/github/palexdev/materialfx/controls/MFXTextField.java#L220
https://github.com/palexdev/MaterialFX/blob/e4573631d7f18fe4febc099eb2a9443719b3b0f8/materialfx/src/main/java/io/github/palexdev/materialfx/controls/MFXPasswordField.java#L162

**Comment by palexdev** [comment]
Should be fixed in latest version
