### ISSUE TITLE
.toList() METHOD NOT FOUND

### ISSUE THREAD

**Issue by emmanpbarrameda** [palexdev/MaterialFX#270]
Based on the MaterialsFX Source Code, the "DEMO CONTROLLER" have .toList() method after return.
But when I tried it on NetBeans, the .toList() method is not found.
I'm using materialfx-11.13.5, JavaFX 11.

I don't know if this a bug, or i make a mistake. Please bear with me and help me. Thank you!

**Screenshots**:
![image](https://user-images.githubusercontent.com/67356375/210093914-8d245b83-9558-48ae-92af-11472e8dbe20.png)

![image](https://user-images.githubusercontent.com/67356375/210094069-42800464-a077-4c71-886a-a8df8e3c00fd.png)
**.toList() not found on suggestion**

![image](https://user-images.githubusercontent.com/67356375/210094170-3701e736-6833-43ae-99af-ecf4e244cbc0.png)
**Code on initializeLoader loader.setOnLoadedAction**

**Comment by palexdev** [comment]
1) I'm guessing your Java version is too old, toList had been added to jdk only recently
2) I suggest you to use IntelliJ Idea instead of that crap, trust me you will love it for Java
