### ISSUE TITLE
MaterialFX in conflict with Ikonli

### ISSUE THREAD

**Issue by HansITChange** [palexdev/MaterialFX#273]
I need for my application other icons from the Ikonli library. 

Icons from Ikonli are showing up with FontIcon(iconcode). However, the 'standard' MaterialFX icons have disappeared.... For instance, in the DatePicker popup...

![image](https://user-images.githubusercontent.com/30934446/210135030-0da69882-44a1-47b8-8a34-76aa29feae10.png)

It looks like the correct font file is not found anymore, once Ikonli is loaded ?
Is it possible to have both libraries in the same application ?

**Comment by palexdev** [comment]
No, MaterialFX use it's own icons set
The thing is, icons are shown through the MFXFontIcon class which uses its own font. Other fonts won't work

**Comment by palexdev** [comment]
I'll mark this as an enhancement, but I'm not sure ok what could be done to improve this.

**Comment by HansITChange** [comment]
Ok, thanks !

**Comment by palexdev** [comment]
@HansITChange hey there, you might want to check out #287

**Comment by palexdev** [comment]
@HansITChange the first version of the new MFXResources module is now available on Maven
