### ISSUE TITLE
MFXFilterComboBox search can't input chinese 

### ISSUE THREAD

**Issue by asd123wto** [palexdev/MaterialFX#284]
![image](https://user-images.githubusercontent.com/31847062/212648139-fc3b3a5e-5c36-4ab3-ae3c-a2cb8cedeb2a.png)

I can't enter Chinese in the search box to search
What method is required for setting?

thank you

**Comment by asd123wto** [comment]
https://github.com/palexdev/MaterialFX/issues/140

**Comment by doublez-ten** [comment]
> ![image](https://user-images.githubusercontent.com/31847062/212648139-fc3b3a5e-5c36-4ab3-ae3c-a2cb8cedeb2a.png)
> 
> I can't enter Chinese in the search box to search What method is required for setting?
> 
> thank you

Use Pinyin to achieve the effect of search,such as:
```
filterCombo.setFilterFunction(new Function<String, Predicate<String>>() {
            @Override
            public Predicate<String> apply(String s) {
                return new Predicate<String>() {
                    @Override
                    public boolean test(String t) {
                        return StringUtils.containsIgnoreCase(PinyinUtil.getPinyin(t), s);
                    }
                };
            }
        });
```
