### ISSUE TITLE
MFXLegacyTableView produces warning when using more than 339 rows

### ISSUE THREAD

**Issue by patrikvalentiny** [palexdev/MaterialFX#291]
**Describe the bug**
When using more than 339 rows and scrolling to the end / clicking on a row while at the bottom of the table a warning is shown 
`PM javafx.scene.control.skin.VirtualFlow addTrailingCellsINFO: index exceeds maxCellCount. 
Check size calculations for class io.github.palexdev.materialfx.controls.legacy.MFXLegacyTableRow`

**To Reproduce**
1. create an MFX table with more than 339 rows
2. scroll to the end
3. if the warning does not show try clicking an item while at the bottom of the table

**Expected behavior**
Does not show error

**Screenshots**
![image](https://user-images.githubusercontent.com/92812102/222560802-89c61045-6503-4037-983b-2ac208e15764.png)

**Comment by palexdev** [comment]
Sorry Legacy components are not a priority
I'll leave this open and mark it appropriately if anyone wants to work on this

This is a bug or JavaFX not MaterialFX

**Comment by palexdev** [comment]
Cannot reproduce after upgrading to JavaFX 19.0.2, maybe the issue was fixed, let me know again by the next version

**Comment by patrikvalentiny** [comment]
Updating to the JavaFX 19.0.2 seems to have fixed the issue for me as well
