### ISSUE TITLE
Useragent Stylesheet system is broken

### ISSUE THREAD

**Issue by Roccoxx** [palexdev/MaterialFX#293]
Hi, it's possible to simplify the change of styles of a element without make a new skin adding the "id" for elements with "setId" method and modify them later in .css style like this [http://www.java2s.com/Code/Java/JavaFX/SetControlIdanduseitincss.htm](url)

And also I want to change the language for some elements for example for the filters text in MFXFilterPaneSkin.java, in my case I'm coding an application in spanish, so I think what with the id of elements I can search them with scene.lookup and modify the text.

**Comment by stefanofornari** [comment]
> Hi, it's possible to simplify the change of styles of a element without make a new skin adding the "id" for elements with "setId" method and modify them later in .css style like this [http://www.java2s.com/Code/Java/JavaFX/SetControlIdanduseitincss.htm](url)

If I well understand what you want to achieve, in most cases you can do it without setting an id, but using control's classes. JavaFX (and therefore MaterialFX) follow quite closely CSS styling. Just be aware of some issues with setUserAgent() as discussed in other topics. 

Anyway, you can set the ids yourself when you create the control.

HTH

**Comment by Roccoxx** [comment]
> If I well understand what you want to achieve, in most cases you can do it without setting an id, but using control's classes. JavaFX (and therefore MaterialFX) follow quite closely CSS styling. Just be aware of some issues with setUserAgent() as discussed in other topics.
> 
> Anyway, you can set the ids yourself when you create the control.

Hi Stefano, thanks for your reply, yes I known, I can set the class or id in controller classes but I need to change the subelements of an elements for example a FilterPane. Look at the class MFXFilterPaneSkin.java, how I can change the text for "filtersLabel", the object has the same class "header-label" that headerLabel.

**Comment by stefanofornari** [comment]
You have to follow the structure and use the proper CSS selector. As you can see in MFXFilterPaneSkin, filtersLabel and the actual headers are in different containers, therefore you can use different selectors.
The other trick is to go through the children yourself:  filterPane.getChildren().get(2) should five you the filtersLabel.

**Comment by Roccoxx** [comment]
Yes I know but theese options produce hardcoding, I think it's better create my own FilterPaneSkin...

**Comment by palexdev** [comment]
Relates to: #232, #225, #294
