### ISSUE TITLE
Maven v1.14.0 gives buggy UI, but v11.14.0-EA3 does not

### ISSUE THREAD

**Issue by Ilirski** [palexdev/MaterialFX#297]
**Describe the bug**

Hi, I'm new to Java, JavaFX, and Maven in general so please excuse any mistakes I make.

I copy the code from `README.md` and added it to my Maven `pom.xml`,

```xml
<dependency>
    <groupId>io.github.palexdev</groupId>
    <artifactId>materialfx</artifactId>
    <version>11.14.0</version>
</dependency>
```

and I add the following scene and call `.show()` on it.
```java
    private Scene createTestScene() {
        VBox vBox = new VBox();
        MFXPasswordField usernameTextField = new MFXPasswordField() {{
            setFloatingText("Inline mode");
        }};
        MFXButton mfxButton = new MFXButton("Submit") {{
            setTextFill(Color.WHITE);
            setButtonType(ButtonType.RAISED);
            setBackground(Background.fill(Color.PURPLE));
        }};
        vBox.getChildren().add(usernameTextField);
        vBox.getChildren().add(mfxButton);
        return new Scene(vBox);
    }
```

I get a broken `MFXPasswordField`:
![image](https://user-images.githubusercontent.com/24876805/225726562-1c860254-b8c5-4b86-863d-2722824e1df8.png)

However when I use version `11.14.0-EA3` instead (which I took from [here](https://mvnrepository.com/artifact/io.github.palexdev/materialfx),

The `MFXPasswordField` works as expected:
![image](https://user-images.githubusercontent.com/24876805/225727005-f3677d4d-58d1-453b-b9f9-a4498567ff0a.png)

Also, I'm new to Maven so I may be mistaken, but the date for the `1.14.x` version looks weird to me (why 2022?)
![image](https://user-images.githubusercontent.com/24876805/225727383-3fbdfd1f-1487-4227-870e-3fd06affdfa2.png)

**Comment by palexdev** [comment]
It's not working because you didn't read the release notes, neither the updated [README](https://github.com/palexdev/MaterialFX#theming-system) ;) 

As for the versions, EA releases stand for Early Access, those two releases come from the staging, and it was intended to be the actual v11.14.0 once completed. I had not enough time to end development though

**Comment by Ilirski** [comment]
Ah I see. So I needed to add 

```java
MFXThemeManager.addOn(scene, Themes.DEFAULT, Themes.LEGACY);
```

for it to be able to show properly. I thought it was a problem with the versions since I couldn't find it on mvnrepository, but turns out it was a problem with me lacking reading skills. Thanks a lot and apologies for the mistake.
