### ISSUE TITLE
It would be even better if the conversation pop-up could be encapsulated into a tool class

### ISSUE THREAD

**Issue by boohsia** [palexdev/MaterialFX#306]
When I tried to encapsulate the dialog box as a tool class, I found that the functionality was normal, except for the lack of masking effects and some very detailed font button styles when the pop-up box appeared. I tried to debug and identify the source of the problem, but it failed. This looked very uncomfortable. I think the session pop-up function is very beautiful, and I hope the person who created it can make it more comfortable to use, Instead of writing repetitive code for all classes that need it

**Comment by palexdev** [comment]
I don't understand your point
1) What are you trying to achieve
2) "Dialog box", "masking effects", "popup box", "session popup". These words are too vague and could mean anything, specify which are the MFX controls that should be enhanced and expose your ideas if you have any
