### ISSUE TITLE
MFXProgressBar not updating progress visually

### ISSUE THREAD

**Issue by mica-alex** [palexdev/MaterialFX#31]
Hi,

I am having an issue updating the progress bar to be any value besides indeterminate. I have run a debug on my application and verified the following: 
1. `progressBar.setProgress( value );` is called from the JavaFX thread
2. The internal `progressBar.progress` and `progressBar.indeterminate` values appear to be properly updated.<br>
![image](https://user-images.githubusercontent.com/83238954/118384099-758e8980-b5d1-11eb-8acd-17392c7eae9b.png)
3. The value specified to `progressBar.setProgress( value )` is either the indeterminate value, or is between 0.0 and 1.0.<br>
![image](https://user-images.githubusercontent.com/83238954/118384145-d027e580-b5d1-11eb-91c9-1b92af5f5f14.png)
4. I have verified that the standard JavaFX progress bar does not experience this behavior, when swapped with the MFXProgressBar (no other code changes)

Despite everything being called and set correctly (I believe), the progress bar always shows as indeterminate in my application.
![image](https://user-images.githubusercontent.com/83238954/118384224-7116a080-b5d2-11eb-8f04-9d68edad7b35.png)

**Comment by palexdev** [comment]
Hello,
Can you provide a reproducible example please?

**Comment by mica-alex** [comment]
Hello @palexdev,

I have created a very basic/simple JavaFX application that can reproduce the error. This basic/simple application uses the same library versions and JavaFX structure I use in the full application.

I did the work in IntelliJ IDEA, although it includes a `pom.xml` file for Maven. All that is required is to run `GUIWindow.main()`, as that extends the JavaFX `Application` class.

[test-jfx-mfx-prog-bar-update-issues.zip](https://github.com/palexdev/MaterialFX/files/6490150/test-jfx-mfx-prog-bar-update-issues.zip)

**Comment by palexdev** [comment]
> Hello @palexdev,
> 
> I have created a very basic/simple JavaFX application that can reproduce the ~error~problem. This basic/simple application uses the same library versions and JavaFX structure I use in the full application.
> 
> I did the work in IntelliJ IDEA, although I includes the `pom.xml` file for Maven as well. All that is required is to run `GUIWindow.main()`, as that extends the JavaFX `Application` class.
> 
> [test-jfx-mfx-prog-bar-update-issues.zip](https://github.com/palexdev/MaterialFX/files/6490150/test-jfx-mfx-prog-bar-update-issues.zip)

Got it, there's a missing listener in the skin
The fix will be included in the next release

https://user-images.githubusercontent.com/16880178/118417834-338b4380-b6b6-11eb-9a85-91eb7f3b73dc.mp4

**Comment by mica-alex** [comment]
Amazing, thank you for the prompt responses and fixes! I am excited for the next release.

**Comment by mica-alex** [comment]
Hi, 

Just to follow up on this, I saw a similar behavior when updating the items on the ComboBox. I do not have a reproducible example of that one though, because I ended up needing to switch GUIs and come back, which bypassed the issue. I’m not sure if I was doing something incorrectly, but I figured I’d mention it. 

Again, thank you for the super quick responses and handling. I’m transitioning my entire application to MaterialFX now because of the ease of use, and I no longer need a collection of add-exports compiler arguments as with JFoenix. Amazing work with MaterialFX!

**Comment by palexdev** [comment]
Can at least tell me if it was LegacyComboBox or the new one?
By updating items you mean changing the items list?

**Comment by mica-alex** [comment]
Sorry for not clarifying. It is the new combo box, and it is when updating items in the items list

**Comment by palexdev** [comment]
Got it, forgot to add the listeners to the items property in case they change
Will fix it in the next release

**Comment by mica-alex** [comment]
Great! Thank you again. I'm glad I found this project.

**Comment by palexdev** [comment]
Fixed in latest release
