### ISSUE TITLE
Controls not showing well

### ISSUE THREAD

**Issue by infinite-dev22** [palexdev/MaterialFX#310]
Something wrong with controls from package io.github.palexdev.mfxcomponents.controls.buttons, These differ from what is seen in SceneBuilder when the App is run.

**SceneBuilder**
![Screenshot from 2023-04-20 02-39-06](https://user-images.githubusercontent.com/77667007/233223067-fa7c6d27-ef33-437e-9448-7945dca8e4ed.png)

**App**
![Screenshot from 2023-04-20 02-42-37](https://user-images.githubusercontent.com/77667007/233223106-c4159603-d6f7-4d18-a55f-7bb7e1580a37.png)

**Comment by palexdev** [comment]
You need to add the Theme on the Scene with MFXThemeManager, for SceneBuilder it is done automaticall

**Comment by infinite-dev22** [comment]
This was added, am following the demo app. I have tried adding a Theme on the very Screen too but nothing is working. Could you show how this can be done best please.

**Comment by palexdev** [comment]
> This was added, am following the demo app. I have tried adding a Theme on the very Screen too but nothing is working. Could you show how this can be done best please.

```java
Scene scene = ...;
MFXThemeManager.PURPLE_LIGHT.addOn(scene);
```

**Comment by infinite-dev22** [comment]
Thank you for the help, I would want to contribute to this Library in the near by time.
Though am not well vast with creating JavaFX Libraries.
