### ISSUE TITLE
Filter doesn't works properly

### ISSUE THREAD

**Issue by Roccoxx** [palexdev/MaterialFX#313]
Hi, i've been tested the filters and I saw a bug when I changed the filters order but with the same objetive and predicates..

First, if I set the follows filters, this works properly

![image](https://user-images.githubusercontent.com/53314419/235371848-2c8250ff-2936-4fde-b4d5-c72513726c58.png)

![image](https://user-images.githubusercontent.com/53314419/235372190-a9500e87-a903-44d7-b1e0-549219606685.png)

But if I only change the order of the filters, this must return the same object but it doesn't works

![image](https://user-images.githubusercontent.com/53314419/235372945-c87987a1-e04a-4395-9f27-65e959718cc1.png)

![image](https://user-images.githubusercontent.com/53314419/235371885-45e3bbbc-51c2-475a-8a77-07fdc2858b9a.png)

**Comment by palexdev** [comment]
This is very strage indeed
Can you provide a reproducer so I can debug the issue?

**Comment by Roccoxx** [comment]
> This is very strage indeed Can you provide a reproducer so I can debug the issue?

Sure. here there is a demo: https://drive.google.com/file/d/1AOAbm8qRETCaFYm1N1tjo5Ycx4-GRlY0/view

**Comment by Roccoxx** [comment]
Hi Alessadro, I tried with a float field also, and I had the same problem, It seems according to the filters order could works fine or bad.

Here is a demo: https://drive.google.com/file/d/1iEyQkSFHI82rq7kExy9QXI5WQAKAofWJ/view

**Comment by Roccoxx** [comment]
Hi, I'am trying debugging the filters (string filters in this case) and I only see that the diference beetween 2 filters order situations are arg$2 (1st and 2nd images) , this is for the selectedPredicateIndex's value.

case 1, start with + contain case:
![image](https://user-images.githubusercontent.com/53314419/236646082-ba1a09df-0ff6-4e5b-b9ab-407ce2787ff6.png)

case 2 contain + start with case: 
![image](https://user-images.githubusercontent.com/53314419/236646147-a20095eb-380a-4e3e-8958-83831fc4cb26.png)

![image](https://user-images.githubusercontent.com/53314419/236645926-4e04a57b-79e9-4b6f-94a1-261f3280543d.png)

**Comment by Roccoxx** [comment]
Hi, because I have a big dick (My friends and others devs call me "Pijudo") I solved this.

Here is the problem explanation:

![image](https://github.com/palexdev/MaterialFX/assets/53314419/09918548-b322-4138-9739-e477ef48412c)

In toFilterBean method (AbstractFilter.java) there is a return for a new FilterBean object with reference "this" for the AbstractFilter. This object is one of the filters of the ComboBox. If you change the predicate index with setSelectedPredicateIndex and you have others filters for the same subject/attribute (Motivo in this case), this replace the predicate's index for all filters because you have reference to the object specified in the ComboBox.  

Here is the very simple solution:

MFXFilterPaneSkin.java

Remove selected.setSelectedPredicateIndex(predicatesCombo.getSelectedIndex());

change FilterBean<T, ?> predicate = selected.toFilterBean(getQuery());

to this FilterBean<T, ?> predicate = selected.toFilterBean(getQuery(), predicatesCombo.getSelectedIndex());

FilterBean.java

`
protected final IntegerProperty selectedPredicateIndex = new SimpleIntegerProperty(-1);

public FilterBean(String query, AbstractFilter<T, U> filter, BiPredicateBean<U, U> predicateBean, int predicateIndex) {
        this(query, filter, predicateBean, ChainMode.OR, predicateIndex);
    }
    
    public FilterBean(String query, AbstractFilter<T, U> filter, BiPredicateBean<U, U> predicateBean, ChainMode mode, int predicateIndex) {
        this.query = query;
        this.filter = filter;
        this.predicateBean = predicateBean;
        this.mode = mode;
        setSelectedPredicateIndex(predicateIndex);
    }
    
    /**
     * Calls {@link AbstractFilter#predicateFor(String, int)} with the query specified by this bean.
     */
    public Predicate<T> predicate() {
        return filter.predicateFor(query, getSelectedPredicateIndex());
    }

 public int getSelectedPredicateIndex() {
        return selectedPredicateIndex.get();
    }

    /**
     * Used to specify the selected {@link BiPredicateBean}.
     */
    public IntegerProperty selectedPredicateIndexProperty() {
        return selectedPredicateIndex;
    }

    public void setSelectedPredicateIndex(int selectedPredicateIndex) {
        this.selectedPredicateIndex.set(selectedPredicateIndex);
    }
`

AbstractFilter.java

`
/**
     * Produces a {@link Predicate} from the given input.
     * <p></p>
     * First checks if a {@link BiPredicate} is selected by checking
     * the selected index property, see {@link #checkIndex(int)}.
     * <p>
     * Then converts the input to an object of type U by using {@link #getValue(String)},
     * and then returns a Predicate that applies the selected BiPredicate to the extracted U field of T
     * and the converted U input.
     * <p></p>
     * In code:
     * <pre>
     * {@code
     *      return t -> biPredicate.test(extractor.apply(t), convertedQuery);
     * }
     * </pre>
     */
    public Predicate<T> predicateFor(String input, int predicateIndex) {
        checkIndex(predicateIndex);
        U convertedInput = getValue(input);
        return t -> predicates.get(predicateIndex).predicate().test(extractor.apply(t), convertedInput);
    }
    
    /**
     * Converts this filter to a {@link FilterBean} from the given input.
     * <p></p>
     * Checks for the selected BiPredicate, see {@link #checkIndex(int)}.
     */
    public FilterBean<T, U> toFilterBean(String input, int predicateIndex) {
        checkIndex(predicateIndex);
        BiPredicateBean<U, U> bean = predicates.get(predicateIndex);
        return new FilterBean<>(input, this, bean, predicateIndex);
    }

    /**
     * Converts this filter to a {@link FilterBean} from the given input and {@link ChainMode}.
     * <p></p>
     * Checks for the selected BiPredicate, see {@link #checkIndex(int}.
     */
    public FilterBean<T, U> toFilterBean(String input, ChainMode mode, int predicateIndex) {
        checkIndex(predicateIndex);
        BiPredicateBean<U, U> bean = predicates.get(predicateIndex);
        return new FilterBean<>(input, this, bean, mode, predicateIndex);
    }

    /**
     * Converts this filter to a {@link FilterBean} from the given input, {@link BiPredicateBean} and {@link ChainMode}.
     */
    public FilterBean<T, U> toFilterBean(String input, BiPredicateBean<U, U> bean, ChainMode mode, int predicateIndex) {
        return new FilterBean<>(input, this, bean, mode, predicateIndex);
    }

    /**
     * Used in methods which rely on a selected {@link BiPredicateBean}.
     *
     * @throws IllegalStateException if the selected index is not valid
     */
    private void checkIndex(int index) throws IllegalStateException {
        if (index < 0) {
            throw new IllegalStateException("No predicate selected for filter: " + name);
        }
    }
`

**Comment by palexdev** [comment]
Fixed in version `11.17.0`, and no, I didn't use your _big dick_ solution
