### ISSUE TITLE
[DatePicker] Change the first day of week

### ISSUE THREAD

**Issue by chuckdu21** [palexdev/MaterialFX#323]
Hi,
Can we change the first day of the week in a datepicker ? I tried to but can't figure it out.

(I'm on the 11.13.10 version because all my custom css doesn't work on latest versions)

**Comment by infinite-dev22** [comment]
Saw this going stale and wanted to help(Incase you haven't yet figured it out yet). So to set the First day of the week in MaterialFX for the ```MFXDatePicker```, use the ```setLocale()``` method of the ```MFXDatePicker``` instance, that will change the display laguage and first day of th week of the Picker.

```
public class Main extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        MFXDatePicker datePicker = new MFXDatePicker();
        
        datePicker.setLocale(Locale.CANADA_FRENCH);  // Set your preferred Locale here.

        HBox root = new HBox(datePicker);

        Scene scene = new Scene(root, 400, 300);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by chuckdu21** [comment]
Thanks a lot !

**Comment by infinite-dev22** [comment]
It's a pleasure, please remember to close this issue.
