### ISSUE TITLE
Demo app opens two black windows on Ubuntu 23.04

### ISSUE THREAD

**Issue by infinite-dev22** [palexdev/MaterialFX#324]
Running the demo app opens two black windows at the Upper left corner of the screen.
![Screenshot from 2023-06-22 05-29-41](https://github.com/palexdev/MaterialFX/assets/77667007/2f6ad3a5-7667-4604-bf5b-4dee9b5bd243)
Closing these makes the notifications not to show. I read through some of the issues here and understand well that the black screens are stages for the notification system, is there another way notifications can be used minus creating these windows.

Can these notifications be made app specific(not to show out of the app as now they seem more of system wide notifications)
![Screenshot from 2023-06-22 06-12-40](https://github.com/palexdev/MaterialFX/assets/77667007/4aef9d22-ed24-45e8-ae20-71b921ea90f6)
![Screenshot from 2023-06-22 06-13-21](https://github.com/palexdev/MaterialFX/assets/77667007/8ce46a96-605f-4a17-9c14-262dc76a94ff)

**Comment by palexdev** [comment]
Fixed thanks to your PR in version `11.17,0`
