### ISSUE TITLE
MFXDatePicker is showing incorrect days.

### ISSUE THREAD

**Issue by j-razeed** [palexdev/MaterialFX#33]
MFXDatePicker is showing incorrect days. i.e., May-2021 is starting on Friday instead of Saturday. Refer image below:

![date](https://user-images.githubusercontent.com/50656721/118513180-15beec80-b751-11eb-94a4-b22d5e25b6ac.png)

**Comment by palexdev** [comment]
I didn't test it enough with other Locales it seems.
I have also fixed another bug. See the circled day? That is supposed to be the current day...lol

![image](https://user-images.githubusercontent.com/16880178/118532838-aee90580-b747-11eb-8a8e-5e0718bedc58.png)

Fixes will be included in the next release
