### ISSUE TITLE
MFXTextField visual bug

### ISSUE THREAD

**Issue by FelipeAumannRS** [palexdev/MaterialFX#330]
MFXTextField "-fx-background-radius" css property does not work. 

![image](https://github.com/palexdev/MaterialFX/assets/26864246/099206c9-8c71-4ab3-9c21-e4717599204f)

**Comment by infinite-dev22** [comment]
A combonation of ```-fx-background-radius``` and ```-fx-border-radius``` should get this resolved. If this doesn't help, kindly edit this and include a MRE(Minimal Reproducable Example) on how this "bug" can be reproduced.

**Comment by FelipeAumannRS** [comment]
Why would you close this? I was about to provide MRE. Using only `-fx-background-radius` *does not work*

**Comment by palexdev** [comment]
1) I thought it was fixed
2) You should have posted a MRE already, I've been very clear in the issue templates

**Comment by FelipeAumannRS** [comment]
@palexdev  that's on me, I haven't checked it before posting. Will be posting mre soon

**Comment by FelipeAumannRS** [comment]
It was an UI bug generated from partial background cropping, happily nothing to do with materialsFX.

Thanks for maintaining such a great library!
