### ISSUE TITLE
MFXCheckBox not rendering, copying CSS works but then makes it not render in lists

### ISSUE THREAD

**Issue by JustTalDevelops** [palexdev/MaterialFX#334]
**Describe the bug**
Using the MFXCheckBox in a sample app, the box around the checkbox does not render. Strangely, copying the CSS for the checkbox into my own app allows it to render but specifically not in list views. I did also notice that clicking on the checkboxes does still cause the ripple animation to play.

**[MRE](https://bit.ly/3k5gTJf)(Minimal Reproducible Example)**
```java
import io.github.palexdev.materialfx.controls.MFXCheckbox;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class MFXSample extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        var listView = new ListView<String>();
        for (int i = 1; i <= 100; i++) {
            listView.getItems().add("Item " + i);
        }

        listView.setCellFactory(param -> new ListCell<>() {
            @Override
            protected void updateItem(String item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                    setGraphic(null);
                } else {
                    var label = new Label(item);
                    var checkbox = new MFXCheckbox();
                    var hBox = new HBox(20, label, checkbox);
                    setGraphic(hBox);
                }
            }
        });

        listView.setStyle("-fx-background-color: #2a3050; -fx-control-inner-background: #2a3050;");

        var vBox = new VBox();
        vBox.getChildren().add(new MFXCheckbox());
        vBox.getChildren().add(listView);

        vBox.setStyle("-fx-background-color: #1e2340;");

        var scene = new Scene(vBox, 300, 400);
        primaryStage.setScene(scene);
        primaryStage.setTitle("MFXCheckBox Sample");
        primaryStage.show();
    }

}
```

**To Reproduce**
1. Run the code.
2. Interact with check-boxes.

**Expected behavior**
For the check-boxes to render fine.

**Comment by palexdev** [comment]
You didn't read the README
You didn't apply MaterialFX theme 😉

**Comment by JustTalDevelops** [comment]
How do I do that? The README doesn't clearly state how to;
> Please, before using this library and submitting an issue complaining that controls are not styled and bugged check how the stilying system has changed since version 11.14.0

Nor does the README state anywhere "how the styling system has changed" since that version. Could you clarify more?

**Comment by JustTalDevelops** [comment]
Ah, through the MFXThemeManager, I see. Thanks.

**Comment by palexdev** [comment]
Yes, there are a bunch of important info in the README, at the `Theming System` section

Beware, the current system may cause performance issues when using MaterialFX dialogs. For this reason, it will drastically change again soon

**Comment by JustTalDevelops** [comment]
It might be a better idea to include that in the important note, a link to that section so it's more clear. Sounds good though.

**Comment by JustTalDevelops** [comment]
So opening up this issue again. Using theme manager and some of the checkboxes seem to load fine, though when scrolling more slowly through the app half of the checkboxes do not render while half do. Here is my updating testing code:

```java
import io.github.palexdev.materialfx.controls.MFXCheckbox;
import io.github.palexdev.materialfx.css.themes.MFXThemeManager;
import io.github.palexdev.materialfx.css.themes.Themes;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class MFXCheckboxInListLayout extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        var listView = new ListView<String>();
        for (int i = 1; i <= 100; i++) {
            listView.getItems().add("Item " + i);
        }

        listView.setCellFactory(param -> new ListCell<>() {
            @Override
            protected void updateItem(String item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                    setGraphic(null);
                } else {
                    var label = new Label(item);
                    var checkbox = new MFXCheckbox();
                    var hBox = new HBox(20, label, checkbox);
                    setGraphic(hBox);
                }
            }
        });

        listView.setStyle("-fx-background-color: #2a3050; -fx-control-inner-background: #2a3050;");

        var vBox = new VBox();
        vBox.getChildren().add(new MFXCheckbox());
        vBox.getChildren().add(listView);

        vBox.setStyle("-fx-background-color: #1e2340;");

        var scene = new Scene(vBox, 300, 400);
        MFXThemeManager.addOn(scene, Themes.DEFAULT);

        primaryStage.setScene(scene);
        primaryStage.setTitle("MFXCheckBox Sample");
        primaryStage.show();
    }

}
```

**Comment by JustTalDevelops** [comment]
@palexdev I see there is a custom listview virtualization system. Are there any docs on this? The wiki does not mention it at all.

**Comment by palexdev** [comment]
> @palexdev I see there is a custom listview virtualization system. Are there any docs on this? The wiki does not mention it at all.

There are two.
One is already included in MaterialFX, it's the MFXListView and it's also present in the wiki

The other is at [VirtualizedFX](https://github.com/palexdev/VirtualizedFX)
This is the latest and greatest implementation that will be utilized in the future in MaterialFX too.
It's a bit more complex to use since it's the building blocks of a List view. But as always, there is a demo, you can check the code to see how it works, documentation is top-notch

**Comment by JustTalDevelops** [comment]
Could you link some relevant demos/docs on the MaterialsFX virtualization system?

There is a wiki page, yes, but it does not help at all with the API and such. There is no equivalent of `setGraphic` and `setText` etc.

**Comment by JustTalDevelops** [comment]
The main thing that is confusing me is that there is no counterpart to `setGraphic`. The way my code currently works is that my list view stores the last state of the cell, and then when the virtualized cell is created, that state is used to create the graphic which is then passed into `setGraphic`. I'm not exactly sure how I would adjust my system to work with the MFX virtualization.

**Comment by JustTalDevelops** [comment]
Okay, so manually setting the children of the cell in an updateItem override seems to work. But I noticed two things:
- The cell width does not scale when the window scales.
- The cell height is not respecting the children's height.

Any ideas? I appreciate your help so much thus far.
