### ISSUE TITLE
Just wanna say keep up the good work!

### ISSUE THREAD

**Issue by Nex-Coder** [palexdev/MaterialFX#34]
Please close this issue whenever!

But I just want to give some morale because i'm loving the look of the project and your changes in staging :)

I'll be switching from JFoenix <3

**Comment by palexdev** [comment]
@Nex-Coder Hello! Thank you very much. It always makes me happy when my projects are actually good and useful for someone else

Sorry if I didn't respond before, but right now I am super focused on the TableView refractor, it's driving me crazy but it's almost there.


Oh a little side note, next time please use Github Discussions if you need to contact me 😉

**Comment by Nex-Coder** [comment]
I was just closing the issue because I didn't wanna add clutter :D Sorry for starting an issue I'm still learning GitHub among other things as a new grad lul. Good luck with your work! Most of my refactoring for MaterialFX is done!

Looking forward to the MFXTableView and MFXPasswordField!
