### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by youngledo** [palexdev/MaterialFX#341]
<img width="1486" alt="image" src="https://github.com/palexdev/MaterialFX/assets/68590897/cf5e0fd8-a72c-44da-b7b7-89609522af53">

**Comment by palexdev** [comment]
Maybe JavaFX version is too low

**Comment by youngledo** [comment]
> Maybe JavaFX version is too low

Hello, I installed version 17.

**Comment by palexdev** [comment]
Yes I see, and I told you it may be too low
But then I see no compilation error other than the IDE popup

**Comment by youngledo** [comment]
> Yes I see, and I told you it may be too low But then I see no compilation error other than the IDE popup

Sorry, The reason is due to the use of incorrect jdk(17.0.8.1.fx-librca).
