### ISSUE TITLE
Setting background color of MFXFilteredComboBox's cells

### ISSUE THREAD

**Issue by FelipeAumannRS** [palexdev/MaterialFX#344]
I'm trying to customize a MFXFilteredComboBox by setting a background color to each individual cell in it. As example, if text is "red", the background color should be red as well.

I tried this implementation below and I did had some progress with it, but it seems to be too much of a pain and I just think it's not worth it to keep going, unless there's a more viable way to achieve what I need.

Here's the code:

`filteredComboBox_colors.setCellFactory(t -> new Cell<>() {
				@Override
				public Node getNode() {
					return new AnchorPane(new Label("Color Name"));
				}

				@Override
				public void updateItem(ProjectsDomain item) {
					if (filteredComboBox_colors.getItems().indexOf(item) == 0)
						getNode().setStyle("-fx-background-color: #1E1E36; -fx-text-fill: #f0f0f0;");
				}`

Btw, I tried looking for it in the MaterialsFX demo project, unfortunately I didn't find any resource which could help me on my request.

**Comment by infinite-dev22** [comment]
Hello, Most list-like components in ```MFX``` are built on top of a ```Virtual Flow```. To color their backgrounds you might want to do it through ```CSS``` to easily access their ```Virtual Flow``` and assign it a background color. In the **Demo App**, this is shown by ```ComboBoxes>New Combos>No Float Custom```. Looking at it's ```CSS``` you find this:
```
#customNCombo2 {
	-fx-border-color: transparent transparent gray transparent;
	-fx-border-radius: 0;
	-fx-padding: 3 -3 0 3;
}

#customNCombo2:focus-within {
	-fx-border-color: transparent transparent -common-gradient transparent;
}

#customNCombo2:focus-within .caret .mfx-font-icon {
	-mfx-color: #ff5d53;
}

#customNCombo2 .virtual-flow {
	-track-color: derive(#ff5d53, 90%);
	-thumb-color: derive(#ff5d53, 50%);
	-thumb-hover-color: derive(#ff5d53, 25%);
}

#customNCombo2 .virtual-flow .mfx-combo-box-cell:hover {
	-fx-background-color: derive(#ff5d53, 90%);
}
```
Try using the above in your application, hope it helps.

**Comment by FelipeAumannRS** [comment]
Hello @infinite-dev22 

Unfortunately it will not work, I can't rely only on css here as I need to set background color based on conditions, so index 0 would have a color, index 1 a different one, and so on

**Comment by infinite-dev22** [comment]
This can still be achieved in a similar way. Write the ```CSS``` handling different colors and have it set as per your conditions using **JFX's** ```getStyleClass().add("your CSS class")```. This calls for the CSS file to be linked to your view.
