### ISSUE TITLE
MFXStepper cancel next()

### ISSUE THREAD

**Issue by DonRecado** [palexdev/MaterialFX#348]
Is there a simple way to stop the MFXStepper from going to the next Toggle even if all the Constraints are valid?

Background:
I would like to make a DB call to check if the given VAT-Number is unique. 
I can bind the call as Constraint, however the call would need to be on the UI-Thread which I would like to avoid. 

The given event BEFORE_NEXT_EVENT has no possibility to cancel the execution of next().

**Comment by palexdev** [comment]
I believe there are two easy ways of doing so:
1) Extending the stepper and change the `next()` method, but I don't know if it's really feasible
2) You could add a Constraint that always starts as false/not met. When you reach the point at which to check it, you could start a background task that communicates with the DB, then update the Constraint with the result. In other words, this solution assumes that you can never go to the next step unless the DB check (done in background) is done and returns true

**Comment by DonRecado** [comment]
> I believe there are two easy ways of doing so:
> 
> 1. Extending the stepper and change the `next()` method, but I don't know if it's really feasible
> 2. You could add a Constraint that always starts as false/not met. When you reach the point at which to check it, you could start a background task that communicates with the DB, then update the Constraint with the result. In other words, this solution assumes that you can never go to the next step unless the DB check (done in background) is done and returns true

Thank you for the quick response.
I already had implemented the second approach, but was thinking that there would be a cleaner solution. 

Overriding the next() method wouldn't solve the problem as the fireEvent() is void. Breaking the method in the middle would require an extra Variable which wouldn't be a clean solution as well.

Will stick to the second approach.

**Comment by palexdev** [comment]
I'll try to remember this if one day is going to be redone/enhanced
Better structured, more modular, maybe no events. Noted 👍🏻
