### ISSUE TITLE
How to use MFXPagination?

### ISSUE THREAD

**Issue by zkycaesar** [palexdev/MaterialFX#355]
### Code:
`MFXPagination pagination = new MFXPagination(10, 5);`
### Effect:
1. At the begin:
![image](https://github.com/palexdev/MaterialFX/assets/17026668/aa23eb64-cd6a-477f-83a9-1f7e8d237686)
2. After clicking the right arrow:
![image](https://github.com/palexdev/MaterialFX/assets/17026668/55f2ad48-f99c-4898-85f6-6a128482bd55)
### Problem:
Where does the 5 extra page tabs come from? Is this a bug?

**Comment by palexdev** [comment]
MFXPagination is buggy and definitely not ready for use
