### ISSUE TITLE
JavaFXThemes & MaterialFXStylesheets don't available on widnows 11

### ISSUE THREAD

**Issue by MaksZys** [palexdev/MaterialFX#369]
**Describe the bug**
Hi I created a project on macOS device but when I moved it to windows 11 it stopped working because of strange this linking issue. 
I tried many maven reset and reinstalls but nothing helped.

**To Reproduce**
1. Create project with materialFX on windows 11 machine

**Expected behavior**
Cannot use `JavaFXThemes` & `MaterialFXStylesheets`

**Screenshots**
<img width="1446" alt="image" src="https://github.com/palexdev/MaterialFX/assets/20974225/bf7fc833-0364-49ba-853c-776452d663a8">

**Comment by palexdev** [comment]
If symbols cannot be found then there's surely something wrong with your dependencies configuration

To confirm that, you could try importing MaterialFX from a local .jar file
For example you could use the materialfx-all release that contains all the modules into a single jar

**Comment by MaksZys** [comment]
Unfortunatlly same effect...

> If symbols cannot be found then there's surely something wrong with your dependencies configuration
> 
> To confirm that, you could try importing MaterialFX from a local .jar file For example you could use the materialfx-all release that contains all the modules into a single jar

**Comment by palexdev** [comment]
What versions are you using?

**Comment by palexdev** [comment]
Ah sorry, 11.17.0 so you are using the version on the `main` branch
Let me see if the issue is present on my end too

**Comment by palexdev** [comment]
@MaksZys 
![image](https://github.com/palexdev/MaterialFX/assets/16880178/c2c8899d-b900-469c-9b6c-b8a5e55b7de0)
It's working on my end

What is strange from your screenshot is that those two classes are shown by IntelliJ with the `.class` extension.
Maybe the jar got corrupted during download? You could try clearing the Maven cache, like actually going in the directory and deleting the jars
