### ISSUE TITLE
MaterialFX Components not displaying correctly

### ISSUE THREAD

**Issue by ejifloy** [palexdev/MaterialFX#372]
Hello,

I have problem with MaterialFX libaray. When I use current version 11.17.0 it does not work correctly:  

| JDK, JavaFX| MaterialFX| Result |
|--------|--------|--------|
| 17/21 | >= 11.14.0 | Scene Builder (21 using 11.17.0 jar) ![preview_fx_2](https://github.com/palexdev/MaterialFX/assets/117834450/8bcdd032-67d8-4d8d-b796-b145e87a8d97)l | 
| 17/21 | >= 11.14.0 | no good look... ![preview_fx_1](https://github.com/palexdev/MaterialFX/assets/117834450/cfe822a4-3851-40f8-8092-6c74f073fe0d)| 
| 17/21 | 11.13.5 | Is look good again!![preview_fx_3](https://github.com/palexdev/MaterialFX/assets/117834450/d333ebcb-e77f-4ee0-8817-db8ca0054145)
 |                                                                                                                                      

I tested the versions downwards till 11.13.5 and with jdk 17 and 21 seperatly. From here it does work for some reason... I would like to use the current version, for the sake of being updated. Any ideas what the problem could be?

IDE: IntelliJ, BuildTools: Maven, OS: Windows 10

Tanks.

**Comment by palexdev** [comment]
You don't know because you didn't read the README nor the documentation ;)
