### ISSUE TITLE
Invisible window when using MFX components.

### ISSUE THREAD

**Issue by chuckdu21** [palexdev/MaterialFX#375]
Hi,

I will try to explain my problem correctly.

When i'm using any MFX components in my app, after the app started there is like an invisible window that appears.

I know that because when i'm clicking on the app window or any other window that is behind this invisible window i lose focus. 

Another trick to detect it, is moving the mouse on all the screen until the cursor changes as resize cursor. It can be in any location of the screen where there are no window borders at all.
I can close this invisible window by right click when my cursor is on resize mode and click on close window and there is no issue after that.

version: 11.13.10 (can't update)
os: ubuntu
i have two screens (one 23" and another 34")

I will record a video soon.

**Comment by palexdev** [comment]
This was fixed by this [commit](https://github.com/palexdev/MaterialFX/commit/a45dcd6fa6ebf342bc33c3eb4c5203d6cfb63201), which is available in the latest version.
Why can't you update?

**Comment by chuckdu21** [comment]
I can't update because you changed a lot about styling component with the next version. It breaks all my front...
Anyway, you commited after last release so

**Comment by palexdev** [comment]
Yeah sorry, I [had to](https://github.com/palexdev/MaterialFX/?tab=readme-ov-file#theming-system)

**Comment by chuckdu21** [comment]
For the demo here is a record of my screen: https://youtu.be/UG4lX7T1ibA

**Comment by palexdev** [comment]
Yes, it is a [known](https://github.com/palexdev/MaterialFX/issues?q=is%3Aissue+corner) bug and as I told you, it's been fixed
