### ISSUE TITLE
MFXFilterPane Modifying

### ISSUE THREAD

**Issue by hdpiscoding** [palexdev/MaterialFX#378]
Hi, 
I'm using MaterialFX (11.13.5) for my JavaFX project at the moment and I want to modify the MFXFilterPane like changing the colors, fonts, text... of the combobox, button, textfield, ...
I've already read the #302 topic but i still can't come up with any ideas. Can you guys give me some solutions?

![Screenshot 2024-04-29 202150](https://github.com/palexdev/MaterialFX/assets/116047729/f68d9d53-966a-4878-a5b1-f503d1f74ce2)

Thanks for spending your time reading my issue!

**Comment by infinite-dev22** [comment]
Hello, can you please share code of what you have done so far... More like an MRE
