### ISSUE TITLE
Request for MFXSpinner

### ISSUE THREAD

**Issue by Aloento** [palexdev/MaterialFX#4]
So, I come here and hope to see the MFXSpinner.
Thank you!!!

**Comment by palexdev** [comment]
@Aloento Hello, sorry for the wait but I'm working on something big
I will take a look at the spinner in the next few days, promise 😄

**Comment by palexdev** [comment]
@Aloento Hello, I have just pushed a new commit on the staging branch that adds the requested spinner
Can you test it and confirm everything works before I merge with the main branch?

**Comment by Aloento** [comment]
Ok I will try to do it

**Comment by garzy** [comment]
Hello, I can't find MFXSpinner on the staging branch. Where is it?

**Comment by palexdev** [comment]
@garzy
I recently realized that there are two completely different spinners.
One is like a progress bar but circular and it's already there, it's MFXProgressSpinner, the other one is that counter component, is that the one you are looking for?

**Comment by garzy** [comment]
I need something control similar to the `the javafx.scene.control.Spinner`, so MFXProgressSpinner it's not what I want.

**Comment by palexdev** [comment]
Got it 👍🏻
Definitely in the roadmap

**Comment by garzy** [comment]
Ohh, thanks!!

**Comment by palexdev** [comment]
Control available in the latest release

Sorry for the delay I always thought you were asking for the MFXProgressSpinner, I didn't get it lol
