### ISSUE TITLE
Unsupported JavaFX configuration

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#40]
I upgraded to new version 11.11.0
but now I receive this error 
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @43586eb9'
Environment : JDK 11
non modular app

**Comment by palexdev** [comment]
Strange, I just tested it with two non-modular apps, and it doesn't throw any error
Can you provide a minimal reproducible example

**Comment by brandonrock919** [comment]
[mfxtest.zip](https://github.com/palexdev/MaterialFX/files/6609490/mfxtest.zip)
Check this please 
I created black project with Gradle and MFX
if you change the MFX version to 11.10.0 the error message will disappear

**Comment by palexdev** [comment]
Closing as it's really an issue
