### ISSUE TITLE
Flowless, Help Wanted

### ISSUE THREAD

**Issue by palexdev** [palexdev/MaterialFX#41]
The project has been recently updated. I always said that I would move Flowless out of the project because it needs ReactFX to be on the classpath which is a rather nasty dependency considering that it's not supported anymore, it's bad written and bad documented. However, many controls such as the new ComboBoxes and the new ListViews rely on Flowless and removing it would also mean to remove those new controls. At first, I even thought about it, but I in the end I decided that it is out of discussion. Those controls are way easier to manage compared to their JavaFX counterparts and while many still use legacy components, personally I always use the new ones because I know exactly how they work, and they are well documented.

So the point is, It would be really a great achievement to remove ReactFX from [Flowless](https://github.com/palexdev/Flowless), but it definitely is a hard task. Flowless is highly dependent on ReactFX, the refactor will require time and knowledge on ReactFX. So I'm here to ask the community if there is someone that would actually try to do it.
The good news at least is that if you don't have ReactFX on the classpath components based on Flowless won't work, but the rest of the library will.

**Comment by Nex-Coder** [comment]
I'm not too knowledgeable with ReactFX and that but I'll have a look at the functionality and see if its something doable by myself. Doubt it, but I'll update you here if I can.

**Comment by Nex-Coder** [comment]
So you need a VirtualFlow object? It is mentioned that there is a undocumented version in JavaFX. But I'm guessing this is no good?

I am actually by coincidence working on something very similar but I hadn't really taken into account rendering efficacy. I'll continue work on the similar object and I'll expand it to meet the functionality that VF applies. That I can do.

Anything else or did I miss the mark? :)

**Comment by mica-alex** [comment]
In addition to the ReactFX issues/limitations described above, it also seems to break JDeps in Java

```
[INFO]             Executing command: cmd.exe /s /c "C:\Users\admin\.jdks\liberica-16.0.1\bin\jdeps -q --multi-release 16 --ignore-missing-deps --print-module-deps "C:\Users\admin\IdeaProjects\launcher\packaging\Launcher\libs"\*.jar "C:\Users\admin\IdeaProjects\launcher\packaging\Launcher-99.9.2021.2-runnable.jar""
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module reactfx not found, required by MaterialFX.materialfx.main
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:900)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```

I am not held back or limited by this, I just simply noticed that this was an issue while I was working on automatic packaging for my application. I'm not super familiar with Java modularization and Jdeps, but I figured it was worth noting this, since I have seen what ReactFX can do recently.

**Comment by palexdev** [comment]
@Nex-Coder Thanks you. JavaFX VirtualFlow is kinda bad, and I'm not talking about performance, at least not only that. You see, I don't only like Flowless because of its performance, I like it for its concept of dummy cells. Many JavaFX controls are utterly cluttered, extending and customizing them is most of the time a pita and that's why I have completely remade many controls from scratch. I want full control over my components because this way they are easier to manage, customize and specialize.

I was also thinking about making my own virtual flow API, but it's easier said than done. Theoretically speaking, the concept of virtual flow quite easy (like I said here [Discussions](https://github.com/palexdev/MaterialFX/discussions/1#discussioncomment-633835)), but the implementation can be quite tricky.

@mica-alex I didn't know that. If I could ditch ReactFX I assure you I would do it now, immediately

**Comment by palexdev** [comment]
Started an attempt: [GitHub](https://github.com/palexdev/VirtualFlowAttempt)

**Comment by palexdev** [comment]
Great news!
My own implementation of a VirtualFlow is finally here: [VirtualizedFX](https://github.com/palexdev/VirtualizedFX)
This means that I can finally remove both Flowless and ReactFX

**Comment by palexdev** [comment]
> In addition to the ReactFX issues/limitations described above, it also seems to break JDeps in Java
> 
> ```
> [INFO]             Executing command: cmd.exe /s /c "C:\Users\admin\.jdks\liberica-16.0.1\bin\jdeps -q --multi-release 16 --ignore-missing-deps --print-module-deps "C:\Users\admin\IdeaProjects\launcher\packaging\Launcher\libs"\*.jar "C:\Users\admin\IdeaProjects\launcher\packaging\Launcher-99.9.2021.2-runnable.jar""
> [ERROR]             Exception in thread "main" java.lang.module.FindException: Module reactfx not found, required by MaterialFX.materialfx.main
> [ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:900)
> [ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
> [ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
> [ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
> [ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
> [ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
> [ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
> [ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
> [ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
> [ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
> ```
> 
> I am not held back or limited by this, I just simply noticed that this was an issue while I was working on automatic packaging for my application. I'm not super familiar with Java modularization and Jdeps, but I figured it was worth noting this, since I have seen what ReactFX can do recently.

With VirtualizedFX I have the same error, but I think it's normal:
```
PS C:\Users\thund\IdeaProjects\MaterialFX\materialfx\build\libs> jdeps --ignore-missing-deps --print-module-deps "C:\Users\thund\Desktop\Programming\lib\jfx-16\lib\*.jar" .\materialfx-11.12.0.jar
Exception in thread "main" java.lang.module.FindException: Module virtualizedfx not found, required by MaterialFX
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
PS C:\Users\thund\IdeaProjects\MaterialFX\materialfx\build\libs> jdeps --ignore-missing-deps --print-module-deps "C:\Users\thund\Desktop\Programming\lib\jfx-16\lib\*.jar" .\materialfx-11.12.0-all.jar
java.base,java.net.http,java.scripting,jdk.jfr,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom
```

As you can see, the command succeeds on the jar that also contains the dependency (it's a shadow jar)
This jar though deletes the module-info.class, this means that it can be used only for non-modular projects, the standard jar can be used only with modular projects as is (since it will automatically download the dependency as well), for non-modular projects I didn't' test it but I think it should work as long as VirtualizedFX is on the classpath too

**Comment by palexdev** [comment]
ReactFX and Flowless have been removed in favor of [VirtualizedFX](https://github.com/palexdev/virtualizedfx)
