### ISSUE TITLE
MFXProgressBar offset bar location after indeterminate

### ISSUE THREAD

**Issue by mica-alex** [palexdev/MaterialFX#44]
Hello,

I have noticed a bug that occurs in certain scenarios with the MFXProgressBar:

When the progress bar is set to indeterminate, then changed to a standard progress value, the location of the bar is sometimes not reset and the standard progress is offset as a result. This does not happen if the progress bar is never set to indeterminate.

<img width="274" alt="ProgressBarIndeterminateToRegular" src="https://user-images.githubusercontent.com/83238954/121189276-f25efd00-c837-11eb-8ffd-2da1d2f4c555.PNG">

https://user-images.githubusercontent.com/83238954/121194929-2ab50a00-c83d-11eb-9baf-1a5007f3f8ef.mp4

**Comment by palexdev** [comment]
I noticed this bug too. But then disappeared, so I hoped to not see it anymore. I don't have any idea on how to solve it honestly because the skin is copied from JFoenix.
I will investigate it further and see what I can discover

**Comment by mica-alex** [comment]
I took a quick look at the skin code and wasn't too sure where the issue is either. 

That being said, I was only using the indeterminate state as a fallback in case my progress manager for some reason did not work. I've just changed to use 0.0 progress now, and I don't see the issue anymore.

**Comment by mica-alex** [comment]
Hey @palexdev,

It looks like the issue has to do with the `scaleX` property on the `bar1` object in the skin. 

I tested locally and was able to see the issue go away by doing *one* of the following:

### Solution 1: Change the 0 index key frame scaleX from `0.7` ->  `1.0`
https://github.com/palexdev/MaterialFX/blob/160f7f3f3d25018b7212b4150bdf31ca88b8f7f3/materialfx/src/main/java/io/github/palexdev/materialfx/skins/MFXProgressBarSkin.java#L112-L116

Would become
```java
KeyFrame kf0 = new KeyFrame(Duration.ZERO,
        new KeyValue(bar1.scaleXProperty(), 1.0),
        new KeyValue(bar1.translateXProperty(), -width),
        new KeyValue(bar2.translateXProperty(), -width)
);
```

### Solution 2: Add a call to `bar1.setScaleX(1.0);` after call to `bar1.setTranslateX(0);` in else state of MFXProgressBarSkin.java#layoutChildren https://github.com/palexdev/MaterialFX/blob/160f7f3f3d25018b7212b4150bdf31ca88b8f7f3/materialfx/src/main/java/io/github/palexdev/materialfx/skins/MFXProgressBarSkin.java#L233-L234

Would become
```java
 bar1.setTranslateX(0);
 bar1.setScaleX(1.0);
 bar2.setTranslateX(0);
```

**Comment by mica-alex** [comment]
I did not test the side effects on the animation of intermediate state when using solution 1. 

I think the best solution is probably number 2, since that one does not have any change or potential side effect on the existing progress bar animation.

**Comment by mica-alex** [comment]
I tested this behavior by doing running the following code (messy, I know, but it did what was needed):

![image](https://user-images.githubusercontent.com/83238954/121554484-35f46b00-c9e0-11eb-9381-872ac822694f.png)

and you can see the result initially forces the bug, and then corrects with scaleX=1.0

https://user-images.githubusercontent.com/83238954/121555139-bf0ba200-c9e0-11eb-823d-37aacaebed18.mp4

**Comment by mica-alex** [comment]
Awesome, thank you!

**Comment by palexdev** [comment]
New version released, can you confirm that now everything works properly?

**Comment by mica-alex** [comment]
Seems good so far -- and the updated progress bar looks good too

**Comment by palexdev** [comment]
Glad you like it 🙂
I can close the issue then, feel free to reopen it or create new ones if you need anything else
