### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FakeException** [palexdev/MaterialFX#47]
I added it to gradle's dependencies but the module-info.java now is getting an error like Package .... reads package 'javafx.beans' from both 'javafx.base' and 'javafx.base' and i can't use the library, also when i try to import something it seems like the package doesn't exists

**Comment by palexdev** [comment]
Hello, can you share a minimal reproducible example?

**Comment by FakeException** [comment]
`plugins {
    id 'application'
    id "org.openjfx.javafxplugin" version "0.0.10"
    id 'org.beryx.jlink' version '2.12.0'
    id "io.freefair.lombok" version "6.0.0-m2"
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.jfoenix:jfoenix:9.0.10'
    compile 'com.zaxxer:HikariCP:4.0.3'
    compile ('io.github.palexdev:materialfx:11.11.1') {
        exclude group: 'org.openjfx'
    }
}

javafx {
    version = "11"
    modules = ['javafx.controls', 'javafx.fxml']
}

mainClassName = "me.darkboy.MainApp"

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'example'
    }
}`

`module Example.main {

    requires transitive javafx.controls;
    requires transitive javafx.fxml;
    requires transitive javafx.graphics;

    requires com.jfoenix;

    requires static lombok;

    requires java.sql;
    requires com.zaxxer.hikari;
    requires java.sql.rowset;

    opens me.darkboy to javafx.fxml;
    opens me.darkboy.controllers to javafx.fxml;

    exports me.darkboy;
    exports me.darkboy.controllers;
    exports me.darkboy.mysql;
    exports me.darkboy.mysql.utils;
    exports me.darkboy.mysql.queries;

}`

**Comment by palexdev** [comment]
Tried to reproduce the issue, but everything seems to work fine
Perhaps there is some issues with your project configuration

**Comment by FakeException** [comment]
can you please send me a sample project like yours just for seeing that everything is working fine

**Comment by palexdev** [comment]
This could be an example [GitHub](https://github.com/palexdev/AddressApp-MVC-DI)
I think it's a Gradle misconfiguration

**Comment by FakeException** [comment]
ok thank you very much

**Comment by FakeException** [comment]
so, i tried with a non modular project and its working, the problem is that with modular projects its not working

**Comment by palexdev** [comment]
Maybe because every module includes JavaFX, maybe this is the issue

**Comment by FakeException** [comment]
yeah i see, i also tried to exclude the javafx dependency from materialfx but it still didn't work

compile ('io.github.palexdev:materialfx:11.11.1') {
exclude group: 'org.openjfx'
}

**Comment by palexdev** [comment]
Is it a compile error or just an IDE error though?

**Comment by FakeException** [comment]
i haven't tried to compile but my ide can't find the materialfx's package

**Comment by FakeException** [comment]
anyway i think i'll stick with a non modular project, thanks for the help.
