### ISSUE TITLE
Unable to Change the Color of the Text in MFXTextField and MFXPasswordField

### ISSUE THREAD

**Issue by Srikeshram** [palexdev/MaterialFX#48]
Hello, I am using the MaterialFX for my Project and I am using the Dark UI. So I want to change **the color of the text** to white based colors of the **MFXTextField** and **MFXPasswordField**. Will you please tell me, Is there any way to change the color of the text in the MFXTextField and MFXPasswordField?

Thanks in Advance.

**Comment by Srikeshram** [comment]
I have found the solution. Shall I contribute it?  Since this is my first PR. So Shall I contribute? @palexdev

**Comment by Srikeshram** [comment]
An another problem is that the icon for the MFXPasswordField is eyeslash but it shows eye as default icon. It can also be fixed by me. Shall I open an PR on this?

**Comment by palexdev** [comment]
> Hello, I am using the MaterialFX for my Project and I am using the Dark UI. So I want to change **the color of the text** to white based colors of the **MFXTextField** and **MFXPasswordField**. Will you please tell me, Is there any way to change the color of the text in the MFXTextField and MFXPasswordField?
> 
> Thanks in Advance.

The text color can be changed by using "-fx-text-fill" in CSS like I did in the demo

**Comment by palexdev** [comment]
> An another problem is that the icon for the MFXPasswordField is eyeslash but it shows eye as default icon. It can also be fixed by me. Shall I open an PR on this?

No, that is the intended behavior, see [Images](https://www.google.it/search?q=password+field&sxsrf=ALeKk00PDEuAfa54oXG0hsOUyecbkVJfKg:1623940106795&source=lnms&tbm=isch&sa=X&ved=2ahUKEwizuM6p8J7xAhUw8bsIHS3QD9oQ_AUoAXoECAEQAw&biw=1920&bih=935#imgrc=Ba9LobA3RRW6LM)

**Comment by Srikeshram** [comment]
Thank You. @palexdev
