### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by mikehearn** [palexdev/MaterialFX#49]
Trying to build from source using `./gradlew run` with Java 11, and I get:

```
> Task :demo:run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /Users/mike/Library/Caches/gradle-build/MaterialFX/demo/classes/java/main
Caused by: java.lang.module.InvalidModuleDescriptorException: null: unnamed package
```

**Comment by palexdev** [comment]
Should be fixed now, let me now 😉

**Comment by mikehearn** [comment]
Works! Really nice work! 

Are there JavaDocs? You've written all your own controls, right, so this isn't so much a JavaFX theme as a complete replacement for the built-in controls. How hard is it to learn?
