### ISSUE TITLE
Runtime Exception while Limiting Characters in MFXPasswordField

### ISSUE THREAD

**Issue by Srikeshram** [palexdev/MaterialFX#50]
When the  ```-mfx-text-limit```  is set to some value, then while running, if the text is entered greater than the spcefied value, it raises an Runtime Exception with the error  ```a bound value cannot be set.``` and it also allows to enter the values greater than the specified value if we catch that exception. Please help me  to resolve the issue.

**Comment by palexdev** [comment]
Ah yes, I didn't test the text limit behavior on password fields, but I know what is causing the issue and how to fix it in the skin class
Will publish the fix as soon as possible

**Comment by Srikeshram** [comment]
Thank You.. Waiting for the fix @palexdev

**Comment by palexdev** [comment]
New version released
