### ISSUE TITLE
Scroll pane can't be scrolled horizontally using the trackpad

### ISSUE THREAD

**Issue by mikehearn** [palexdev/MaterialFX#51]
In the demo app section scrollpane preview, the one with the horizontal track doesn't respond to sideways swiping with the Mac track pad.

**Comment by palexdev** [comment]
Known issue. Unfortunately, the smooth scrolling code is taken from JFoenix, it's not my work and I don't know how it works.
I will try to fix it, but it's not a priority. Implementing smooth scrolling in JavaFX seems to be quite hard.

**Comment by palexdev** [comment]
New version released
