### ISSUE TITLE
ListView trackpad inertia too high

### ISSUE THREAD

**Issue by mikehearn** [palexdev/MaterialFX#53]
In the demo app, in the font resources section, there's a list view. Trying to scroll with the trackpad is quite hard because the friction is too low, so even a tiny swipe causes the list to fly all the way to the end. It requires a truly tiny swipe to move the list by less than the whole amount. It feels like the inertial physics of this control don't match the operating system defaults.

**Comment by palexdev** [comment]
Known issue.
A possible solution would be to reduce the scroll speed when the event comes from the trackpad. A possible solution if only JavaFX  offered a way to differentiate between mouse and trackpad, so I don't have any idea on how to fix this

**Comment by mikehearn** [comment]
Look at `GestureEvent.isDirect` - this method is oddly named, but a non-direct event is one that comes from a touch pad.

https://openjfx.io/javadoc/16/javafx.graphics/javafx/scene/input/GestureEvent.html#isDirect()

**Comment by palexdev** [comment]
New version released
