### ISSUE TITLE
Slider control

### ISSUE THREAD

**Issue by vonZeppelin** [palexdev/MaterialFX#54]
Hi,

Are there any plans to provide a Slider control?

Thank you!

**Comment by palexdev** [comment]
Yes, it's in the [ROADMAP](https://github.com/palexdev/MaterialFX/blob/main/ROADMAP.md)

**Comment by palexdev** [comment]
Keep it open as a reminder
I'll close the issue when the control is added

**Comment by palexdev** [comment]
New version released
