### ISSUE TITLE
Validators not updating

### ISSUE THREAD

**Issue by AigleDev** [palexdev/MaterialFX#58]
Hi, i'm using MaterialFX with TornadoFX on JDK 16 and it seems like the validators doesn't update when selecting another component and the message doesn't show either, i have downloaded the demo and it works but when using it on my project it doesn't so i assumed that there something wrong with my code:

```kotlin
fun MFXTextField.markAsRequired(): MFXTextField {
    validator.add(
        BindingUtils.toProperty(Bindings.createBooleanBinding({ return@createBooleanBinding !text.isNullOrBlank() }, textProperty())),
        "Ce champ est obligatoire"
    )
    isValidated = false
    return this
}

fun MFXTextField.markAsDoubleOnly(): MFXTextField {
    validator.add(
        BindingUtils.toProperty(Bindings.createBooleanBinding({ return@createBooleanBinding text != null && text.isDouble() }, textProperty())),
        "Type incorrecte, précisez un décimal"
    )
    isValidated = false
    return this
}```

**Comment by palexdev** [comment]
I think the issue is the `isValidated` flag
For validated controls that flag must be set to true in order to enable the validator

**Comment by AigleDev** [comment]
Thank you very much, indeed that was the issue
