### ISSUE TITLE
Enhancement: Closely Match Material Style Guidelines

### ISSUE THREAD

**Issue by zgover** [palexdev/MaterialFX#59]
Tip: Would be great to have this library provide default theme styles which match much closer to the [Material.io Design Guidelines](https://material.io/design). Aside from that, looks good, kudos!

**Comment by palexdev** [comment]
All controls follow as much as possible Material.io guidelines, do you have any particular control which should be reviewed?

**Comment by zgover** [comment]
@palexdev you are correct they do follow the guidelines. Rather I was referring to the specific presentation styles of the system default  demonstrations of components on material.io, to closely provide an immediate visual correlation amongst your adopters. This philosophy is often harnessed in consumer markets to create a behavioral pattern which supports triggering familiarity, which itself can identify many variables all mostly positive. To further detail, it's a would be a recommended practice to provide the material as defaults and allow the adopter or themeing to override with modifications. The characteristics in highest contrast evident of distinction would be theme colors (*gradients I do believe I mistaked the headings in the photos for actionable items), border radius (e.g., dialog, notification), icon (e.g., tight gutters in lists, resolution in fields.), toggle buttons, and dpi. (Do take note I am almost positive the images having mismatching resolution are playing with my eyes so I could be wrong about some of the items listed.) 

**Closing**
