### ISSUE TITLE
Dialogs not working and PasswordField bug

### ISSUE THREAD

**Issue by FakeException** [palexdev/MaterialFX#60]
`MFXDialog dialog = new MFXDialog();
dialog.setContent("test");
dialog.show();`

When i try to show a dialog i get this error:

> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1862)
> 	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1729)
> 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
> 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
> 	at javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.scene.Node.fireEvent(Node.java:8889)
> 	at javafx.scene.control.Button.fire(Button.java:203)
> 	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
> 	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
> 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
> 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
> 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
> 	at javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
> 	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
> 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
> 	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
> 	at com.sun.glass.ui.View.notifyMouse(View.java:942)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
> 	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
> 	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
> 	... 46 more
> Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.layout.Pane.widthProperty()" because "parent" is null
> 	at io.github.palexdev.materialfx.effects.MFXScrimEffect.modalScrim(MFXScrimEffect.java:77)
> 	at io.github.palexdev.materialfx.controls.MFXDialog.show(MFXDialog.java:153)
> 	at me.darkboy.controllers.RegisterController.onRegisterClick(RegisterController.java:28)
> 	... 58 more
> Caused by: java.lang.reflect.InvocationTargetException
> 
> Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.layout.Pane.widthProperty()" because "parent" is null

When i use a passwordfield with a length limit and i get to the end, if i continue to type after reaching the limit it still allows me to type and i get this error:

> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: A bound value cannot be set.
> 	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1391)
> 	at javafx.scene.control.TextInputControl.setText(TextInputControl.java:361)
> 	at io.github.palexdev.materialfx.controls.MFXTextField.lambda$addListeners$3(MFXTextField.java:183)
> 	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1459)
> 	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1463)
> 	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1402)
> 	at javafx.scene.control.TextInputControl.lambda$new$0(TextInputControl.java:146)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:91)
> 	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1264)
> 	at javafx.scene.control.TextInputControl.filterAndSet(TextInputControl.java:1229)
> 	at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1480)
> 	at javafx.scene.control.TextInputControl$TextProperty$Listener.invalidated(TextInputControl.java:1503)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:175)
> 	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
> 	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
> 	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
> 	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
> 	at io.github.palexdev.materialfx.skins.MFXPasswordFieldSkin.setFakeText(MFXPasswordFieldSkin.java:330)
> 	at io.github.palexdev.materialfx.skins.MFXPasswordFieldSkin.lambda$setListeners$1(MFXPasswordFieldSkin.java:113)
> 	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
> 	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:221)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
> 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
> 	at javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.scene.Scene$KeyHandler.process(Scene.java:4064)
> 	at javafx.scene.Scene.processKeyEvent(Scene.java:2123)
> 	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2591)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
> 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
> 	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
> 	at com.sun.glass.ui.View.notifyKey(View.java:971)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:831)

i am using Java 16

**Comment by palexdev** [comment]
Since MFXDialogs are basically a Border pane they need to be added to the children list of the pane on which it will be shown.
Take a look at the dialogs demo controller for some code example.

For the password field issue it has been already reported here [#50](https://github.com/palexdev/MaterialFX/issues/50) and the fix has been pushed on the staging branch

**Comment by FakeException** [comment]
ok thanks
