### ISSUE TITLE
License Agreement

### ISSUE THREAD

**Issue by alaa-az** [palexdev/MaterialFX#61]
Any chance you will change your licence agreement in the future so I can consider this library for my closed source projects?

**Comment by palexdev** [comment]
Yes, the license will be changed to LGPL in the next update

**Comment by alaa-az** [comment]
Thanks alot

**Comment by objectProgrammer** [comment]
Hi @palexdev, I'd like to recommend the GPL license with the classpath exception just like the JDK and JavaFX. LGPL includes some C-specific wording like static/dynamic links, so I believe GPL+CE is better.
