### ISSUE TITLE
How can I change the label text in the tableView？

### ISSUE THREAD

**Issue by Cydianrice** [palexdev/MaterialFX#64]
How should I modify the text in the red box?(Without modify the jar file or remake the jar from the source)
Can I add a listenner when user change the settings of the RowsPerPage?
I am a student from China who is studying your progrom to finish my java application.

![image](https://user-images.githubusercontent.com/24198335/124557485-25fb6a00-de6c-11eb-852a-a998b3406f48.png)

**Comment by palexdev** [comment]
As of now there's no way
I'll add the css selectors in the next update
Marking the issue as enhancement

**Comment by Cydianrice** [comment]
I think maybe in the future ,this project can add more languages.
Right now , the default menu only provides  the text in English.
I fix this problem by remaking the jar.

**Comment by palexdev** [comment]
Internationalization in another enhancement that I want to make, but for now it's not high priority

**Comment by palexdev** [comment]
@Cydianrice Can you open a separate issue for internationalization?

**Comment by palexdev** [comment]
New version released
