### ISSUE TITLE
SceneBuilder cannot be imported 

### ISSUE THREAD

**Issue by WanManito** [palexdev/MaterialFX#65]
![image](https://user-images.githubusercontent.com/26118508/124693456-0e76bc80-df12-11eb-8751-230eaaa91dc9.png)

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/124693734-80e79c80-df12-11eb-87cb-73d07d443b3f.png)

**Comment by palexdev** [comment]
SceneBuilder version?

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/124845840-2578e580-dfca-11eb-908b-30a37297603b.png)
@palexdev

**Comment by palexdev** [comment]
My library requires Java 11+
So you need at least Scene Builder 11
