### ISSUE TITLE
Where is the dependency? 

### ISSUE THREAD

**Issue by ahmadbintariq4u** [palexdev/MaterialFX#67]

**Comment by palexdev** [comment]
What?

**Comment by ahmadbintariq4u** [comment]
Sir, I mean where is the maven dependency?

**Comment by ahmadbintariq4u** [comment]
Is the library available on maven central? or I have to use JDK file?

**Comment by palexdev** [comment]
It's all written in the README file
It's not optional to read it you know

**Comment by ahmadbintariq4u** [comment]
@palexdev  haha sorry sir, I did not scroll anymore. Thanks.
