### ISSUE TITLE
Module reactfx not found, required by MaterialFX

### ISSUE THREAD

**Issue by justadev0** [palexdev/MaterialFX#68]
I'm building a modular application and I am getting the following error.
`Error occurred during initialization of boot layer java.lang.module.FindException: Module reactfx not found, required by MaterialFX.`
Error is identical for gradle and IDE runs

Reactfx has definitely been downloaded by gradle as I can see it in the external libraries section. Below is my Gradle build file

```
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.5.10'
    id 'application'
}
group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
def javaFXPlatform = getJavaFXPlatform()
def javaFXVersion = "16"
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
    implementation 'io.github.palexdev:materialfx:11.11.1'
    implementation "org.openjfx:javafx-base:${javaFXVersion}:${javaFXPlatform}"
    implementation "org.openjfx:javafx-controls:${javaFXVersion}:${javaFXPlatform}"
    implementation "org.openjfx:javafx-graphics:${javaFXVersion}:${javaFXPlatform}"
    implementation "org.openjfx:javafx-fxml:${javaFXVersion}:${javaFXPlatform}"
}

application {
    mainModule.set('main')
    mainClass.set('application.MainApp')
}
test {
    useJUnitPlatform()
}
java {
    modularity.inferModulePath.set(true)
}
private static String getJavaFXPlatform() {
    return 'win'
}
```
And my module-info.java file

`module main {
    requires MaterialFX;
    requires javafx.graphics;
    requires javafx.fxml;
    requires javafx.controls;
    requires kotlin.stdlib;
    opens application;
}`

JavaFX is working fine without MaterialFX. Thank you, I really appreciate all the work you've put in to this library, i'm really hoping I can fix this issue and be rid of Jfoenix forever!

**Comment by palexdev** [comment]
You must also add ReactFX to the dependencies even if it is already downloaded

**Comment by justadev0** [comment]
Added the dependency as suggested however the issue remains the same. Apologies as I am quite new to Gradle, would adding it like this in the build file be sufficient?
`implementation group: 'org.reactfx', name: 'reactfx', version: '2.0-M5'`
Once I add this and then add a `requires reactfx;` to the module-info file I get the error that it can't find reactfx so perhaps I have included the dependency incorrectly?

**Comment by palexdev** [comment]
MaterialFX itself is a modular project
You can take a look at the build.gradle and module info files here

Links: [Gradle](https://github.com/palexdev/MaterialFX/blob/main/materialfx/build.gradle), [ModuleInfo](https://github.com/palexdev/MaterialFX/blob/main/materialfx/src/main/java/module-info.java)

For projects that require MaterialFX new list views and combo boxes, reactfx must be on the classpath

So the dependency should be added for every module that requires MaterialFX

**Comment by palexdev** [comment]
I'm working to remove ReactFX and Flowless from MaterialFX, but as of now it's easier said than done, see [Issue #41](https://github.com/palexdev/MaterialFX/issues/41)

**Comment by justadev0** [comment]
After adding the dependency in the build.gradle file I added reactfx to the module-info file and now get an error in this file on the line where i require reactfx of `error: module not found`. I looked into the files you linked but was not able to change anything to solve the issue i'm having, probably due to my inexperience with gradle. Any help at all would be greatly appreciated. Below is my project structure for reference if that is of any use.

```
main (module)
     java
          application
               ---
          module-info.java
     kotlin
          (empty as of now)
test (module)
     ----
```

**Comment by justadev0** [comment]
An update for anyone who was in the same position as me, I managed to fix this by creating a new project and not having a module-info.java file as well as removing `mainModule.set('main')` from the build.gradle file. Not sure if that was the right way to go about it but it fixed the issue.
