### ISSUE TITLE
How can I add a imageview (or other nodes) into a TreeCell ?

### ISSUE THREAD

**Issue by Cydianrice** [palexdev/MaterialFX#70]
I note that in the demo ,there is no examples about treeView.
But I find the node MFXTreeView in the MaterialFX.
I had tried to use it, but not like the MFXTableView , it cannot use the function of setCellFactory to add the nodes like imageView and so on.
So, how can I do it ?
(I am a student from China , so my English is not so good.I am sorry about that.)

**Comment by Cydianrice** [comment]
I am using the version 11.11.1

**Comment by palexdev** [comment]
There are examples of tree view
The sidebar follows alphabetical order, keep scrolling till the end
And there's even a tree view which uses HBoxes as item
Code examples are in the demo as usual: [Controller](https://github.com/palexdev/MaterialFX/blob/main/demo/src/main/java/io/github/palexdev/materialfx/demo/controllers/TreeviewsDemoController.java)

**Comment by Cydianrice** [comment]
Could you add a gif into the README.md?
I have  problems when I try to run the demo.

**Comment by Cydianrice** [comment]
I got it.
Thank you.
