### ISSUE TITLE
Fluent API on components

### ISSUE THREAD

**Issue by Juke1999** [palexdev/MaterialFX#78]
It would be great to have the possibility to use Java's fluent API on all components. If you create a button, you won't have to do:
```Java
MFXButton loginButton = new MFXButton();

loginButton.setText("Login");
loginButton.setGraphic(new FontIcon("fas-sign-in-alt"));
loginButton.setButtonType(ButtonType.RAISED);
loginButton.setTranslateY(50);
loginButton.setGraphicTextGap(10);
loginButton.getStyleClass().add("some-class");
```
but instead:
```Java
MFXButton loginButton = new MFXButton()
    .setText("Login")
    .setGraphic(new FontIcon("fas-sign-in-alt"))
    .setButtonType(ButtonType.RAISED)
    .setTranslateY(50)
    .setGraphicTextGap(10)
    .getStyleClass().add("some-class");
```

This would make the code cleaner and the creation of new elements a lot easier.

**Comment by palexdev** [comment]
Fluent API is more suitable for builders
Using it everywhere would be an  anti-pattern
What do you think of a ComponentBuilder which gives instances of other builders for each component, for example:

```
ComponentBuilder.getButtonBuilder()
        .setText(...)
        .setGraphic(...)
        and so on...

ComponentBuilder.getCheckboxBuilder()
        .setText(...)
       .setSelected(...)
       and so on...
```
This way would be more clean, but still, a lot of code to write for each component

**Comment by Juke1999** [comment]
That should work, indeed.
It was just a suggestion, it more or less works like your code too, that's true.

**Comment by palexdev** [comment]
I'm going to mark this as enhancement then
Hope to get it done for the next version

**Comment by palexdev** [comment]
Available on staging branch
Hope I didn't forgot anything and that the API is convenient enough

**Comment by palexdev** [comment]
API available in the latest release
