### ISSUE TITLE
Feature Request - ScaledContentPane

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#79]
There is cool library that can be useful for development 
this resolve a lot of scaling headache for scalable elements and Linux 4K screens
https://github.com/miho/ScaledFX
I think it could be amazing if you will add this too
Thanks :) (you are doing amazing work)

**Comment by palexdev** [comment]
Will look into that, after all it's just a class, won't be hard

Thanks :)

**Comment by palexdev** [comment]
Now available in the latest release
