### ISSUE TITLE
Notification on minimized screen

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#80]
There is a issue when we a long task and we minimized the app
The notification will not displayed because he don't have and owner window
`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Owner window must not be null`

**Comment by palexdev** [comment]
I'm going to review the entire system in the next version, I'll keep this in mind

**Comment by palexdev** [comment]
New notification systems available in the latest release
