### ISSUE TITLE
MFXTableView Filters

### ISSUE THREAD

**Issue by brandonrock919** [palexdev/MaterialFX#81]
I think it will be great if you can add dynamically all the table columns to the filters options
then the user can filter by custom columns
similar to this 
![SCN_Filter](https://user-images.githubusercontent.com/64746247/126052679-af79cbf1-282d-4684-8ea7-e76b1482ff6e.png)

**Comment by palexdev** [comment]
Maybe it's possible, maybe.
Because columns are just "dumb" nodes, they know nothing about the represented data. They just have a text property for their name and some other properties but nothing about data.

I'll see what I can do

**Comment by palexdev** [comment]
MFXFilterPane is now available
Table views now depend on that to filter the content, it is much more flexible and powerful
