### ISSUE TITLE
Bug - Scroll bar issue with legacy TableView

### ISSUE THREAD

**Issue by Tech-Expert-Wizard** [palexdev/MaterialFX#83]
I was trying out some things in the demo, and I got to the legacy TableView, where I dragged one column far enough that the horizontal scroll bar would show up, and then I dragged it back, and the horizontal scroll bar was still there.
![Screenshot of bug](https://user-images.githubusercontent.com/77369194/126201132-24e90a96-5a87-41ef-8036-d00d4267bbc0.png)

**Comment by palexdev** [comment]
I will investigate the issue and see what I can do

**Comment by palexdev** [comment]
Fixed, changes are available on the staging branch
Same issue fixed for list views too

**Comment by palexdev** [comment]
Fixes available in latest release
