### ISSUE TITLE
combobox setting selected value

### ISSUE THREAD

**Issue by warmuuh** [palexdev/MaterialFX#84]
Using combobox, something is off with setting the selectedValue, example code:
```java
public class Test extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        var root = FxmlBuilder.vbox();
        Scene mainScene = new Scene(root);

        mainScene.getStylesheets().clear();
        mainScene.getStylesheets().add("/mfx/light.css");

        root.add(new Label("MFXComboBox"));
        var nmfx = new MFXComboBox<>();
        nmfx.getItems().add("a");
        nmfx.getItems().add("b");
        nmfx.getItems().add("c");
        nmfx.setSelectedValue("b");
//        Platform.runLater(() -> nmfx.setSelectedValue("b"));
        root.add(nmfx);


        primaryStage.setScene(mainScene);
        primaryStage.show();
    }
}
```
this results in an empty combo-box being rendered (as in: no value selected). using `Platform.runLater(() -> nmfx.setSelectedValue("b"));` instead, the value is now there but the value is not highlighted as selected in the list-view:
![image](https://user-images.githubusercontent.com/1331628/126182049-e6e8985b-e856-4985-8d4b-69eb2ec41138.png)

once manually selecting a value, the value and selected item in list are in sync

one more difference to other comboboxes (MFXLegacyComboBox, ComboBox or JFXComboBox) is that dropdown doesnt close once window looses focus, but that might be not an issue at all

**Comment by palexdev** [comment]
My bad, I should delete that method and make the property read only.
You are doing it the wrong way. To select an item you must use the selection model.
So: `nmfx.getSelectionModel().selectItem("b");`

**Comment by warmuuh** [comment]
ok, that works... just mentioning: also `nmfx.getSelectionModel().setSelectedItem(...)` doesnt work, could maybe a bit streamlined

**Comment by palexdev** [comment]
Almost done :)

![Work](https://user-images.githubusercontent.com/16880178/133670705-9edce663-a40b-4094-b4d7-4dd78d129aa9.gif)

**Comment by palexdev** [comment]
Fixes available on staging branch, I think I'll make some more improvement though

**Comment by palexdev** [comment]
MFXComboBoxes have been reworked in latest release
Many improvements to selection, and values set have been made
