### ISSUE TITLE
converters for combobox

### ISSUE THREAD

**Issue by warmuuh** [palexdev/MaterialFX#85]
it would be nice to have similar support for converters as in base javafx, see ComboBox->converter-property.

usecase: it is not always feasable to use toString of the objects inside a comboBox

**Comment by palexdev** [comment]
I know I marked it as a low priority improvement
I will introduce them at some point

**Comment by palexdev** [comment]
MFXComboBoxes have been reworked in latest release, converters have been implemented
Issue fixed
