### ISSUE TITLE
Setting MFXDatePicker value

### ISSUE THREAD

**Issue by justadev0** [palexdev/MaterialFX#86]
How do you set the value for MFXDatePicker programatically? I have tried `dateBox.getDatePicker().setValue(LocalDate.parse(textDate, dateformatter));` as well as `dateBox.getDatePicker().setValue(LocalDate.now());` but neither work. Technically getting the datepickercontent and setting the date like this `dateBox.getContent().setCurrentDate(LocalDate.parse(textDate, dateformatter));` works in that the text box value is set but when you open up the calendar it shows the current date (month and year) rather than the one that was set (even after calling `refresh()` on the datepickercontent. 
Even reinitializing the object with the new date seems to not do anything. Have I missed anything?

**Comment by justadev0** [comment]
I found a fix. First, setting the value in currentDateProperty.
`datePicker.getContent().currentDateProperty().set(localDate);`
This will only change the value stored but not shown to the user. Only doing this was resulting in the calendar still showing today's date when clicked on. To change the calender I did
`datePicker.getContent().setYearMonth(YearMonth.from(localDate));`
This set's the calendar month/year correctly but the only thing missing is that the day has not been set which I have not yet found a fix for however it solves most of the problems I was facing

**Comment by palexdev** [comment]
That's what happens when you copy JavaFX shit

You know what, I'm gonna remake the DatePicker from scratch, as it is now it's confusing an buggy, I'll make it simple and user-friendly

**Comment by palexdev** [comment]
MFXDatePicker has been reworked in latest release, issue should be fixed

**Comment by justadev0** [comment]
Hey, loving the new version but i'm not sure how exactly to implement this now. I use `datePicker.setValue(someDate)` but that does not update in the textField, only in the calendar. However if I were to translate the datepicker to a different location, it does show the date on the textField. Is there any update method i need to call after programatically setting the date?

**Comment by palexdev** [comment]
@justadev0 I juste tested it to check if I forgot some listener or something like that, but it works

https://user-images.githubusercontent.com/16880178/157567192-a9cb0727-7c2b-45fb-a99c-db8b3eab9b16.mp4

**Comment by justadev0** [comment]
I am able to replicate the behaviour you've described where if i set the value on a button click then it sets on the text field without issue. But if I were to set it programatically when the page has loaded, it does not show in the textField. As an example in your code, it would be something like doing `pick.setValue(randomDate)` after `primaryStage.show()`. Does that work for you? Maybe it has to do with javafx in general and the visual elements may have not been loaded properly at the time? I'm not too sure really
