### ISSUE TITLE
Error on compile and run

### ISSUE THREAD

**Issue by tretonis** [palexdev/MaterialFX#88]
Linux Ubuntu 20.04

openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.25.0, JRE 16 Linux amd64-64-Bit Compressed References 20210311_69 (JIT enabled, AOT enabled)
OpenJ9   - 022d65424
OMR      - 09514431e
JCL      - 0c11227a21a based on jdk-16+36)

-----------------------------------------------------------
Gradle 6.8.1
------------------------------------------------------------

Build time:   2021-01-22 13:20:08 UTC
Revision:     31f14a87d93945024ab7a78de84102a3400fa5b2

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16 (Eclipse OpenJ9 openj9-0.25.0)
OS:           Linux 5.8.0-63-generic amd64

>>>>>>>>>>>>>>>>>>>>>
./gradlew build 

display error

> Configure project :
Project :demo => 'MaterialFX.Demo' Java module
Project :materialfx => 'MaterialFX' Java module

> Task :materialfx:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':materialfx:compileJava'.
> java.lang.IllegalAccessError: A classe org/gradle/internal/compiler/java/ClassNameCollector(unnamed module 0x00000000E3447EE0) não pode acessar a classe com/sun/tools/javac/code/Symbol$TypeSymbol(module jdk.compiler) porque o módulo module jdk.compiler não exporta o pacote com/sun/tools/javac/code para o módulo unnamed module 0x00000000E3447EE0

**********************
I confess that gradle has left me very confused with the errors and how to solve them.

Could you please enlighten me about the correct settings
to be able to compile and run?

Thanks.

**Comment by palexdev** [comment]
I would need to setup Ubuntu in a VM to try reproducing the issue

From the error though it seems to be related to bad system or Gradle configuration
