### ISSUE TITLE
MFXListView customcell selection

### ISSUE THREAD

**Issue by OoALRAi** [palexdev/MaterialFX#89]
Hi,
when I implement customCell the MFXListView selection does not work anymore. tried to debug it by tracing the selectionModeProperty but it look like the property does not change no matter how much i click on the items.

**Comment by palexdev** [comment]
Can you show me the custom cell code please?

**Comment by OoALRAi** [comment]
package com.ilyas;

import io.github.palexdev.materialfx.controls.MFXListView;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.*;
import javafx.util.Callback;

import java.io.IOException;

public class Controller2 {

    @FXML
    MFXListView<Item> listView;

    public void initialize(){
        listView.setCellFactory(new Callback<ListView<Item>, ListCell<Item>>() {
            @Override
            public ListCell<Item> call(ListView<Item> param) {
                return new CustomCell();
            }
        });
        listView.selectionModelProperty().addListener(((observable, oldValue, newValue) -> {
            System.out.println(newValue.getSelectedItem());
        }));
    }

    class CustomCell extends ListCell<Item>{

        ItemController controller;
        Parent parent;

        public CustomCell() {
            try {
                FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/ilyas/item.fxml"));
                parent = loader.load();
                controller = loader.getController();
                //
                // controller.deleteButton.setOnAction(e-> getListView().getItems().remove(getItem()));
            }catch (Exception ignored){
                ignored.printStackTrace();
            }
        }

        @Override
        protected void updateItem(Item item, boolean empty) {
            super.updateItem(item, empty);
            setGraphic(null);
            if (!empty){
                controller.setName(item.getName());
                controller.setAge(item.getAge());
                setGraphic(parent);
            }
            getListView().getSelectionModel().selectAll();
        }
    }

    class Item {
        String name;
        int age;

        public Item(String name, int age){
            this.name = name;
            this.age = age;
        }

        public String getName(){
            return this.name;
        }

        public int getAge(){
            return this.age;
        }

        @Override
        public String toString() {
            return "Item{" +
                    "name='" + name + '\'' +
                    ", age=" + age +
                    '}';
        }
    }

    public void add(){
        listView.getItems().add(new Item("ilyas", 26));
    }

}

**made a fxml scene that contains only the listview and add button, with this code as a controller**

**Comment by palexdev** [comment]
Oooh so you are using MFXListView, I thought you were using the new implementation based on Flowless

I'll investigate the issue, in the meanwhile you could try using the new list view (MFXFlowlessListView)

**Comment by OoALRAi** [comment]
there is no need to check it, i was implementing the javafx original ListCell. thanks to let me know about the new MFXFlowlessLIstView.
sorry aobut that :)

**Comment by palexdev** [comment]
> there is no need to check it, i was implementing the javafx original ListCell. thanks to let me know about the new MFXFlowlessLIstView.
> sorry aobut that :)

No problem 👍
Closing the issue then
