### ISSUE TITLE
Add entry to JFXCentral

### ISSUE THREAD

**Issue by dlemmermann** [palexdev/MaterialFX#97]
Would be great if this library could be added to JFXCentral at jfx-central.com. Data needs to be added to the data repository: https://github.com/dlemmermann/jfxcentral-data

**Comment by palexdev** [comment]
Very interesting, as soon as I have some free time I'll take a look

**Comment by dlemmermann** [comment]
We are getting more and more traffic. Your entry would be much appreciated.
