### ISSUE TITLE
MFXPasswordField setOnKeyPressed is not listening

### ISSUE THREAD

**Issue by Nekoer** [palexdev/MaterialFX#98]
Nothing happens when I press enter

`password.setOnKeyPressed {
            if (it.code == KeyCode.ENTER){
                login()
            }
        }
`

**Comment by palexdev** [comment]
Fixed
The fix will be available in the next minor release

**Comment by palexdev** [comment]
MFXPasswordField has been reworked in latest release, issue should be fixed
