### ISSUE TITLE
MFXPasswordField not showing hide characters

### ISSUE THREAD

**Issue by Luposz** [palexdev/MaterialFX#99]
I have a MFXPasswordField and a button to auto-generate a password.
Right now I'm using this "mypassword.passwordProperty().set(autogeneratedpassword)"

The MFXPasswordField is blank, but if I click the eye, it's possible to see the password there.
![Git2](https://user-images.githubusercontent.com/89623719/131069905-7a00fc59-6f65-43b5-96f6-948879ab9d61.PNG)
![Git1](https://user-images.githubusercontent.com/89623719/131069908-d93ca9b4-9e9d-40ed-a012-e4b89333f9dc.PNG)

**Comment by palexdev** [comment]
Fixed, changes are available on the staging branch

**Comment by Luposz** [comment]
Thank you so much!

**Comment by palexdev** [comment]
MFXPassword field has been reworked in latest release, issue should be resolved
